/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  ConflictError,
  CreateLabelInput,
  ErrorResponse,
  GetLabelsParams,
  InternalError,
  LabelListResponse,
  LabelResponse,
  NotfoundError,
  UpdateLabelInput
} from '../../schemas';

import { axiosInstance } from '../../configs/axios-instance';




/**
 * Create a new label
 */
export const postLabels = (
    createLabelInput: CreateLabelInput,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<LabelResponse>(
      {url: `/labels`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLabelInput, signal
    },
      );
    }
  


export const getPostLabelsMutationOptions = <TError = ErrorResponse | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLabels>>, TError,{data: CreateLabelInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postLabels>>, TError,{data: CreateLabelInput}, TContext> => {

const mutationKey = ['postLabels'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLabels>>, {data: CreateLabelInput}> = (props) => {
          const {data} = props ?? {};

          return  postLabels(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLabelsMutationResult = NonNullable<Awaited<ReturnType<typeof postLabels>>>
    export type PostLabelsMutationBody = CreateLabelInput
    export type PostLabelsMutationError = ErrorResponse | ConflictError | InternalError

    export const usePostLabels = <TError = ErrorResponse | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLabels>>, TError,{data: CreateLabelInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLabels>>,
        TError,
        {data: CreateLabelInput},
        TContext
      > => {

      const mutationOptions = getPostLabelsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Get all labels with pagination and filtering
 */
export const getLabels = (
    params: GetLabelsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<LabelListResponse>(
      {url: `/labels`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetLabelsQueryKey = (params?: GetLabelsParams,) => {
    return [`/labels`, ...(params ? [params]: [])] as const;
    }

    
export const getGetLabelsQueryOptions = <TData = Awaited<ReturnType<typeof getLabels>>, TError = InternalError>(params: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLabelsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLabels>>> = ({ signal }) => getLabels(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLabelsQueryResult = NonNullable<Awaited<ReturnType<typeof getLabels>>>
export type GetLabelsQueryError = InternalError


export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = InternalError>(
 params: GetLabelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabels>>,
          TError,
          Awaited<ReturnType<typeof getLabels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = InternalError>(
 params: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabels>>,
          TError,
          Awaited<ReturnType<typeof getLabels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = InternalError>(
 params: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = InternalError>(
 params: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLabelsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get a single label by ID
 */
export const getLabelsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<LabelResponse>(
      {url: `/labels/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetLabelsIdQueryKey = (id?: string,) => {
    return [`/labels/${id}`] as const;
    }

    
export const getGetLabelsIdQueryOptions = <TData = Awaited<ReturnType<typeof getLabelsId>>, TError = ErrorResponse | NotfoundError | InternalError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLabelsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLabelsId>>> = ({ signal }) => getLabelsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLabelsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLabelsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLabelsId>>>
export type GetLabelsIdQueryError = ErrorResponse | NotfoundError | InternalError


export function useGetLabelsId<TData = Awaited<ReturnType<typeof getLabelsId>>, TError = ErrorResponse | NotfoundError | InternalError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelsId>>,
          TError,
          Awaited<ReturnType<typeof getLabelsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabelsId<TData = Awaited<ReturnType<typeof getLabelsId>>, TError = ErrorResponse | NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelsId>>,
          TError,
          Awaited<ReturnType<typeof getLabelsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabelsId<TData = Awaited<ReturnType<typeof getLabelsId>>, TError = ErrorResponse | NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLabelsId<TData = Awaited<ReturnType<typeof getLabelsId>>, TError = ErrorResponse | NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLabelsIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update a label
 */
export const patchLabelsId = (
    id: string,
    updateLabelInput: UpdateLabelInput,
 ) => {
      
      
      return axiosInstance<LabelResponse>(
      {url: `/labels/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateLabelInput
    },
      );
    }
  


export const getPatchLabelsIdMutationOptions = <TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchLabelsId>>, TError,{id: string;data: UpdateLabelInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchLabelsId>>, TError,{id: string;data: UpdateLabelInput}, TContext> => {

const mutationKey = ['patchLabelsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchLabelsId>>, {id: string;data: UpdateLabelInput}> = (props) => {
          const {id,data} = props ?? {};

          return  patchLabelsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchLabelsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchLabelsId>>>
    export type PatchLabelsIdMutationBody = UpdateLabelInput
    export type PatchLabelsIdMutationError = ErrorResponse | NotfoundError | ConflictError | InternalError

    export const usePatchLabelsId = <TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchLabelsId>>, TError,{id: string;data: UpdateLabelInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchLabelsId>>,
        TError,
        {id: string;data: UpdateLabelInput},
        TContext
      > => {

      const mutationOptions = getPatchLabelsIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Delete a label
 */
export const deleteLabelsId = (
    id: string,
 ) => {
      
      
      return axiosInstance<BaseResponse>(
      {url: `/labels/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteLabelsIdMutationOptions = <TError = ErrorResponse | NotfoundError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLabelsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteLabelsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteLabelsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLabelsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteLabelsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteLabelsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLabelsId>>>
    
    export type DeleteLabelsIdMutationError = ErrorResponse | NotfoundError | InternalError

    export const useDeleteLabelsId = <TError = ErrorResponse | NotfoundError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLabelsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLabelsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteLabelsIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    