/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Create a new inventory item
 */
export const postInventoriesBodyDiscountPercentMin = 0;

export const postInventoriesBodyDiscountPercentMax = 100;
export const postInventoriesBodyInStockMin = 0;
export const postInventoriesBodyLowStockThresholdMin = 0;
export const postInventoriesBodyWarehouseCodeMaxOne = 200;
export const postInventoriesBodyShelfCodeMaxOne = 200;
export const postInventoriesBodyHsCodeMaxOne = 200;
export const postInventoriesBodyOriginCountryMaxOne = 200;
export const postInventoriesBodyPackageDimensionsMaxOne = 200;


export const postInventoriesBody = zod.object({
  "storeId": zod.uuid().describe('Store ID'),
  "locationId": zod.uuid().describe('Location ID'),
  "variantId": zod.uuid().describe('Variant ID'),
  "guaranteeId": zod.union([zod.uuid(),zod.null()]).optional().describe('Guarantee ID'),
  "insuranceId": zod.union([zod.uuid(),zod.null()]).optional().describe('Insurance ID'),
  "leasingId": zod.union([zod.uuid(),zod.null()]).optional().describe('Leasing ID'),
  "chequeId": zod.union([zod.uuid(),zod.null()]).optional().describe('Cheque ID'),
  "cost": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Cost price'),
  "price": zod.coerce.number().describe('Base price'),
  "discountPercent": zod.coerce.number().min(postInventoriesBodyDiscountPercentMin).max(postInventoriesBodyDiscountPercentMax).describe('Discount percentage'),
  "discountPrice": zod.coerce.number().describe('Price after discount (calculated)'),
  "inStock": zod.coerce.number().min(postInventoriesBodyInStockMin).describe('Current stock quantity'),
  "lowStockThreshold": zod.coerce.number().min(postInventoriesBodyLowStockThresholdMin).describe('Low stock alert threshold'),
  "expiryDate": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Expiry date for perishable items'),
  "warehouseCode": zod.union([zod.coerce.string().max(postInventoriesBodyWarehouseCodeMaxOne),zod.null()]).optional().describe('Warehouse code'),
  "shelfCode": zod.union([zod.coerce.string().max(postInventoriesBodyShelfCodeMaxOne),zod.null()]).optional().describe('Shelf code for location in warehouse'),
  "hsCode": zod.union([zod.coerce.string().max(postInventoriesBodyHsCodeMaxOne),zod.null()]).optional().describe('Harmonized System code for customs'),
  "originCountry": zod.union([zod.coerce.string().max(postInventoriesBodyOriginCountryMaxOne),zod.null()]).optional().describe('Country of manufacture/origin'),
  "packageWeight": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Gross weight including packaging (kg)'),
  "packageDimensions": zod.union([zod.coerce.string().max(postInventoriesBodyPackageDimensionsMaxOne),zod.null()]).optional().describe('Packaged dimensions: length x width x height')
}).describe('Inventory creation payload')

/**
 * List all inventory items with pagination and filters
 */
export const getInventoriesQueryFieldDefaultOne = "createdAt";
export const getInventoriesQueryFieldMaxOne = 200;
export const getInventoriesQueryOrderDefaultOne = "desc";export const getInventoriesQuerySkipMin = 0;
export const getInventoriesQueryLimitMax = 20;
export const getInventoriesQueryWarehouseCodeMaxOne = 200;


export const getInventoriesQueryParams = zod.object({
  "field": zod.union([zod.coerce.string().max(getInventoriesQueryFieldMaxOne),zod.null()]).optional().describe('Field to sort by'),
  "order": zod.union([zod.enum(['asc', 'desc']),zod.null()]).optional().describe('Sort order'),
  "skip": zod.coerce.number().min(getInventoriesQuerySkipMin).describe('Number of records to skip'),
  "limit": zod.coerce.number().min(1).max(getInventoriesQueryLimitMax).describe('Maximum number of records to return'),
  "storeId": zod.union([zod.uuid(),zod.null()]).optional().describe('Filter by store ID'),
  "locationId": zod.union([zod.uuid(),zod.null()]).optional().describe('Filter by location ID'),
  "variantId": zod.union([zod.uuid(),zod.null()]).optional().describe('Filter by variant ID'),
  "warehouseCode": zod.union([zod.coerce.string().max(getInventoriesQueryWarehouseCodeMaxOne),zod.null()]).optional().describe('Filter by warehouse code'),
  "minPrice": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Minimum price'),
  "maxPrice": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Maximum price'),
  "minCost": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Minimum price'),
  "maxCost": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Maximum price'),
  "minInStock": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Minimum stock quantity'),
  "maxInStock": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Maximum stock quantity'),
  "isLowStock": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Filter by low stock status')
})

export const getInventoriesResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('List of inventories response')

/**
 * Get a single inventory item by ID
 */
export const getInventoriesIdParams = zod.object({
  "id": zod.uuid().describe('Inventory ID')
})

export const getInventoriesIdResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('Single inventory response')

/**
 * Update an inventory item
 */
export const patchInventoriesIdParams = zod.object({
  "id": zod.uuid().describe('Inventory ID')
})

export const patchInventoriesIdBodyDiscountPercentMin = 0;

export const patchInventoriesIdBodyDiscountPercentMax = 100;
export const patchInventoriesIdBodyInStockMin = 0;
export const patchInventoriesIdBodyLowStockThresholdMin = 0;
export const patchInventoriesIdBodyWarehouseCodeMaxOne = 200;
export const patchInventoriesIdBodyShelfCodeMaxOne = 200;
export const patchInventoriesIdBodyHsCodeMaxOne = 200;
export const patchInventoriesIdBodyOriginCountryMaxOne = 200;
export const patchInventoriesIdBodyPackageDimensionsMaxOne = 200;


export const patchInventoriesIdBody = zod.object({
  "storeId": zod.uuid().optional().describe('Store ID'),
  "locationId": zod.uuid().optional().describe('Location ID'),
  "variantId": zod.uuid().optional().describe('Variant ID'),
  "guaranteeId": zod.union([zod.uuid(),zod.null()]).optional().describe('Guarantee ID'),
  "insuranceId": zod.union([zod.uuid(),zod.null()]).optional().describe('Insurance ID'),
  "leasingId": zod.union([zod.uuid(),zod.null()]).optional().describe('Leasing ID'),
  "chequeId": zod.union([zod.uuid(),zod.null()]).optional().describe('Cheque ID'),
  "cost": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Cost price'),
  "price": zod.coerce.number().optional().describe('Base price'),
  "discountPercent": zod.coerce.number().min(patchInventoriesIdBodyDiscountPercentMin).max(patchInventoriesIdBodyDiscountPercentMax).optional().describe('Discount percentage'),
  "discountPrice": zod.coerce.number().optional().describe('Price after discount (calculated)'),
  "inStock": zod.coerce.number().min(patchInventoriesIdBodyInStockMin).optional().describe('Current stock quantity'),
  "lowStockThreshold": zod.coerce.number().min(patchInventoriesIdBodyLowStockThresholdMin).optional().describe('Low stock alert threshold'),
  "expiryDate": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Expiry date for perishable items'),
  "warehouseCode": zod.union([zod.coerce.string().max(patchInventoriesIdBodyWarehouseCodeMaxOne),zod.null()]).optional().describe('Warehouse code'),
  "shelfCode": zod.union([zod.coerce.string().max(patchInventoriesIdBodyShelfCodeMaxOne),zod.null()]).optional().describe('Shelf code for location in warehouse'),
  "hsCode": zod.union([zod.coerce.string().max(patchInventoriesIdBodyHsCodeMaxOne),zod.null()]).optional().describe('Harmonized System code for customs'),
  "originCountry": zod.union([zod.coerce.string().max(patchInventoriesIdBodyOriginCountryMaxOne),zod.null()]).optional().describe('Country of manufacture/origin'),
  "packageWeight": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Gross weight including packaging (kg)'),
  "packageDimensions": zod.union([zod.coerce.string().max(patchInventoriesIdBodyPackageDimensionsMaxOne),zod.null()]).optional().describe('Packaged dimensions: length x width x height')
}).describe('Inventory update payload')

export const patchInventoriesIdResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('Single inventory response')

/**
 * Soft delete an inventory item
 */
export const deleteInventoriesIdParams = zod.object({
  "id": zod.uuid().describe('Inventory ID')
})

