/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

/**
 * Create a new province
 */
export const postProvincesBodyNameMin = 2;
export const postProvincesBodyNameMax = 50;
export const postProvincesBodyAbbMaxOne = 200;

export const postProvincesBody = zod
  .object({
    name: zod.coerce
      .string()
      .min(
        postProvincesBodyNameMin,
        `نام استان باید حداقل ${postProvincesBodyNameMin} کاراکتر باشد`,
      )
      .max(
        postProvincesBodyNameMax,
        `نام استان نمی‌تواند بیش از ${postProvincesBodyNameMax} کاراکتر باشد`,
      )
      .describe("نام استان (الزامی)"),
    abb: zod
      .union([
        zod.coerce
          .string()
          .max(
            postProvincesBodyAbbMaxOne,
            `اختصار استان نمی‌تواند بیش از ${postProvincesBodyAbbMaxOne} کاراکتر باشد`,
          ),
        zod.null(),
      ])
      .optional()
      .describe("اختصار استان (اختیاری)"),
    countryId: zod
      .uuid("شناسه کشور معتبر نیست")
      .describe("شناسه کشور والد (الزامی)"),
  })
  .describe("ساختار ایجاد استان");

/**
 * Get all provinces with pagination and filters
 */
export const getProvincesQueryFieldDefaultOne = "createdAt";
export const getProvincesQueryFieldMaxOne = 200;
export const getProvincesQueryOrderDefaultOne = "desc";
export const getProvincesQuerySkipMin = 0;
export const getProvincesQueryLimitMax = 20;
export const getProvincesQueryNameMaxOne = 200;
export const getProvincesQueryAbbMaxOne = 200;

export const getProvincesQueryParams = zod.object({
  field: zod
    .union([zod.coerce.string().max(getProvincesQueryFieldMaxOne), zod.null()])
    .optional()
    .describe("مرتب‌سازی بر اساس فیلد (اختیاری)"),
  order: zod
    .union([zod.enum(["asc", "desc"]), zod.null()])
    .optional()
    .describe("ترتیب مرتب‌سازی (asc یا desc)"),
  skip: zod.coerce
    .number()
    .min(
      getProvincesQuerySkipMin,
      `مقدار skip نمی‌تواند کمتر از ${getProvincesQuerySkipMin} باشد`,
    )
    .describe("تعداد رکورد‌هایی که رد می‌شود (برای صفحه‌بندی)"),
  limit: zod.coerce
    .number()
    .min(1, "حداقل مقدار limit یک است")
    .max(
      getProvincesQueryLimitMax,
      `limit نمی‌تواند بیشتر از ${getProvincesQueryLimitMax} باشد`,
    )
    .describe("حداکثر تعداد رکوردهای قابل دریافت"),
  name: zod
    .union([zod.coerce.string().max(getProvincesQueryNameMaxOne), zod.null()])
    .optional()
    .describe("فیلتر بر اساس نام استان"),
  abb: zod
    .union([zod.coerce.string().max(getProvincesQueryAbbMaxOne), zod.null()])
    .optional()
    .describe("فیلتر بر اساس اختصار استان"),
  countryId: zod
    .union([zod.uuid("شناسه کشور معتبر نیست"), zod.null()])
    .optional()
    .describe("فیلتر بر اساس شناسه کشور"),
});

export const getProvincesResponse = zod
  .object({
    success: zod
      .union([zod.coerce.boolean(), zod.null()])
      .optional()
      .describe("وضعیت عملیات"),
  })
  .describe("ساختار استاندارد پاسخ API برای لیست استان‌ها");

/**
 * Get a single province by ID
 */
export const getProvincesIdParams = zod.object({
  id: zod.uuid().describe("شناسه استان"),
});

export const getProvincesIdResponse = zod
  .object({
    success: zod.union([zod.coerce.boolean(), zod.null()]).optional(),
  })
  .describe("ساختار استاندارد پاسخ API برای دریافت یک استان");

/**
 * Update a province
 */
export const patchProvincesIdParams = zod.object({
  id: zod.uuid().describe("شناسه استان"),
});

export const patchProvincesIdBodyNameMin = 2;
export const patchProvincesIdBodyNameMax = 50;
export const patchProvincesIdBodyAbbMaxOne = 200;

export const patchProvincesIdBody = zod
  .object({
    name: zod.coerce
      .string()
      .min(
        patchProvincesIdBodyNameMin,
        `نام استان باید حداقل ${patchProvincesIdBodyNameMin} کاراکتر باشد`,
      )
      .max(
        patchProvincesIdBodyNameMax,
        `نام استان نمی‌تواند بیش از ${patchProvincesIdBodyNameMax} کاراکتر باشد`,
      )
      .optional()
      .describe("نام استان (اختیاری)"),
    abb: zod
      .union([
        zod
          .string()
          .max(
            patchProvincesIdBodyAbbMaxOne,
            `اختصار استان نمی‌تواند بیش از ${patchProvincesIdBodyAbbMaxOne} کاراکتر باشد`,
          ),
        zod.null(),
      ])
      .optional()
      .describe("اختصار استان (اختیاری)"),
    countryId: zod
      .uuid("شناسه کشور معتبر نیست")
      .optional()
      .describe("شناسه کشور والد (اختیاری)"),
  })
  .describe("ساختار به‌روزرسانی استان");

export const patchProvincesIdResponse = zod
  .object({
    success: zod.union([zod.coerce.boolean(), zod.null()]).optional(),
  })
  .describe("ساختار استاندارد پاسخ API برای ویرایش استان");

/**
 * Delete a province
 */
export const deleteProvincesIdParams = zod.object({
  id: zod.uuid().describe("شناسه استان"),
});
