/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  ConflictError,
  CreatePricingTierInput,
  ErrorResponse,
  GetPricingTiersParams,
  InternalError,
  NotfoundError,
  PricingTierListResponse,
  PricingTierResponse,
  UpdatePricingTierInput,
} from "../../schemas";

import { axiosInstance } from "../../configs/axios-instance";

/**
 * Create a new pricing tier
 */
export const postPricingTiers = (
  createPricingTierInput: CreatePricingTierInput,
  signal?: AbortSignal,
) => {
  return axiosInstance<PricingTierResponse>({
    url: `/pricing-tiers`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createPricingTierInput,
    signal,
  });
};

export const getPostPricingTiersMutationOptions = <
  TError = ErrorResponse | ConflictError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPricingTiers>>,
    TError,
    { data: CreatePricingTierInput },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPricingTiers>>,
  TError,
  { data: CreatePricingTierInput },
  TContext
> => {
  const mutationKey = ["postPricingTiers"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPricingTiers>>,
    { data: CreatePricingTierInput }
  > = (props) => {
    const { data } = props ?? {};

    return postPricingTiers(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPricingTiersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPricingTiers>>
>;
export type PostPricingTiersMutationBody = CreatePricingTierInput;
export type PostPricingTiersMutationError = ErrorResponse | ConflictError;

export const usePostPricingTiers = <
  TError = ErrorResponse | ConflictError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPricingTiers>>,
      TError,
      { data: CreatePricingTierInput },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPricingTiers>>,
  TError,
  { data: CreatePricingTierInput },
  TContext
> => {
  const mutationOptions = getPostPricingTiersMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all pricing tiers with pagination and filtering
 */
export const getPricingTiers = (
  params: GetPricingTiersParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<PricingTierListResponse>({
    url: `/pricing-tiers`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetPricingTiersQueryKey = (params?: GetPricingTiersParams) => {
  return [`/pricing-tiers`, ...(params ? [params] : [])] as const;
};

export const getGetPricingTiersQueryOptions = <
  TData = Awaited<ReturnType<typeof getPricingTiers>>,
  TError = InternalError,
>(
  params: GetPricingTiersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiers>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPricingTiersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPricingTiers>>> = ({
    signal,
  }) => getPricingTiers(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPricingTiers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPricingTiersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPricingTiers>>
>;
export type GetPricingTiersQueryError = InternalError;

export function useGetPricingTiers<
  TData = Awaited<ReturnType<typeof getPricingTiers>>,
  TError = InternalError,
>(
  params: GetPricingTiersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPricingTiers>>,
          TError,
          Awaited<ReturnType<typeof getPricingTiers>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPricingTiers<
  TData = Awaited<ReturnType<typeof getPricingTiers>>,
  TError = InternalError,
>(
  params: GetPricingTiersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPricingTiers>>,
          TError,
          Awaited<ReturnType<typeof getPricingTiers>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPricingTiers<
  TData = Awaited<ReturnType<typeof getPricingTiers>>,
  TError = InternalError,
>(
  params: GetPricingTiersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetPricingTiers<
  TData = Awaited<ReturnType<typeof getPricingTiers>>,
  TError = InternalError,
>(
  params: GetPricingTiersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPricingTiersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPricingTiersId = (id: string, signal?: AbortSignal) => {
  return axiosInstance<PricingTierResponse>({
    url: `/pricing-tiers/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetPricingTiersIdQueryKey = (id?: string) => {
  return [`/pricing-tiers/${id}`] as const;
};

export const getGetPricingTiersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPricingTiersId>>,
  TError = NotfoundError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiersId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPricingTiersIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPricingTiersId>>
  > = ({ signal }) => getPricingTiersId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPricingTiersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPricingTiersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPricingTiersId>>
>;
export type GetPricingTiersIdQueryError = NotfoundError;

export function useGetPricingTiersId<
  TData = Awaited<ReturnType<typeof getPricingTiersId>>,
  TError = NotfoundError,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPricingTiersId>>,
          TError,
          Awaited<ReturnType<typeof getPricingTiersId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPricingTiersId<
  TData = Awaited<ReturnType<typeof getPricingTiersId>>,
  TError = NotfoundError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPricingTiersId>>,
          TError,
          Awaited<ReturnType<typeof getPricingTiersId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPricingTiersId<
  TData = Awaited<ReturnType<typeof getPricingTiersId>>,
  TError = NotfoundError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiersId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetPricingTiersId<
  TData = Awaited<ReturnType<typeof getPricingTiersId>>,
  TError = NotfoundError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPricingTiersId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPricingTiersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const patchPricingTiersId = (
  id: string,
  updatePricingTierInput: UpdatePricingTierInput,
) => {
  return axiosInstance<PricingTierResponse>({
    url: `/pricing-tiers/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updatePricingTierInput,
  });
};

export const getPatchPricingTiersIdMutationOptions = <
  TError = ErrorResponse | NotfoundError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchPricingTiersId>>,
    TError,
    { id: string; data: UpdatePricingTierInput },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchPricingTiersId>>,
  TError,
  { id: string; data: UpdatePricingTierInput },
  TContext
> => {
  const mutationKey = ["patchPricingTiersId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchPricingTiersId>>,
    { id: string; data: UpdatePricingTierInput }
  > = (props) => {
    const { id, data } = props ?? {};

    return patchPricingTiersId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchPricingTiersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchPricingTiersId>>
>;
export type PatchPricingTiersIdMutationBody = UpdatePricingTierInput;
export type PatchPricingTiersIdMutationError = ErrorResponse | NotfoundError;

export const usePatchPricingTiersId = <
  TError = ErrorResponse | NotfoundError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchPricingTiersId>>,
      TError,
      { id: string; data: UpdatePricingTierInput },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchPricingTiersId>>,
  TError,
  { id: string; data: UpdatePricingTierInput },
  TContext
> => {
  const mutationOptions = getPatchPricingTiersIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deletePricingTiersId = (id: string) => {
  return axiosInstance<BaseResponse>({
    url: `/pricing-tiers/${id}`,
    method: "DELETE",
  });
};

export const getDeletePricingTiersIdMutationOptions = <
  TError = NotfoundError | ConflictError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePricingTiersId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePricingTiersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deletePricingTiersId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePricingTiersId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deletePricingTiersId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePricingTiersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePricingTiersId>>
>;

export type DeletePricingTiersIdMutationError = NotfoundError | ConflictError;

export const useDeletePricingTiersId = <
  TError = NotfoundError | ConflictError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePricingTiersId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePricingTiersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeletePricingTiersIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
