/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Create a new color
 */
export const postColorsBodyNameMax = 50;
export const postColorsBodyEnNameMaxOne = 200;
export const postColorsBodyDisplayNameMaxOne = 200;
export const postColorsBodyHexRegExp = new RegExp('^#([0-9A-Fa-f]{3}){1,2}$');


export const postColorsBody = zod.object({
  "name": zod.coerce.string().min(1).max(postColorsBodyNameMax).describe('Category name in native language'),
  "enName": zod.union([zod.coerce.string().max(postColorsBodyEnNameMaxOne),zod.null()]).optional().describe('English name for internationalization'),
  "displayName": zod.union([zod.coerce.string().max(postColorsBodyDisplayNameMaxOne),zod.null()]).optional().describe('for marketing. e.g: \'Snow white\''),
  "hex": zod.coerce.string().regex(postColorsBodyHexRegExp).describe('Hexadecimal color code (e.g., #FFFFFF, #FF5733)'),
  "isActive": zod.coerce.boolean().describe('Filter by active status')
}).describe('Color creation payload')

/**
 * Get all colors with pagination and filters
 */
export const getColorsQueryFieldDefaultOne = "createdAt";
export const getColorsQueryFieldMaxOne = 200;
export const getColorsQueryOrderDefaultOne = "desc";export const getColorsQuerySkipMin = 0;
export const getColorsQueryLimitMax = 20;
export const getColorsQueryNameMaxOne = 200;
export const getColorsQueryEnNameMaxOne = 200;
export const getColorsQueryDisplayNameMaxOne = 200;
export const getColorsQueryHexMaxOne = 7;

export const getColorsQueryHexRegExpOne = new RegExp('^#([0-9A-Fa-f]{3}){1,2}$');


export const getColorsQueryParams = zod.object({
  "field": zod.union([zod.coerce.string().max(getColorsQueryFieldMaxOne),zod.null()]).optional().describe('Field to sort by'),
  "order": zod.union([zod.enum(['asc', 'desc']),zod.null()]).optional().describe('Sort order'),
  "skip": zod.coerce.number().min(getColorsQuerySkipMin).describe('Number of records to skip'),
  "limit": zod.coerce.number().min(1).max(getColorsQueryLimitMax).describe('Maximum number of records to return'),
  "deletedAt": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Optional date input, usually null'),
  "name": zod.union([zod.coerce.string().max(getColorsQueryNameMaxOne),zod.null()]).optional().describe('Filter by color name in native language'),
  "enName": zod.union([zod.coerce.string().max(getColorsQueryEnNameMaxOne),zod.null()]).optional().describe('Filter by English color name for internationalization'),
  "displayName": zod.union([zod.coerce.string().max(getColorsQueryDisplayNameMaxOne),zod.null()]).optional().describe('Filter by marketing display name (e.g., \'Snow white\')'),
  "hex": zod.union([zod.coerce.string().max(getColorsQueryHexMaxOne).regex(getColorsQueryHexRegExpOne),zod.null()]).optional().describe('Filter by hexadecimal color code (e.g., #FFFFFF, #FF5733)'),
  "isActive": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Filter by active status')
})

export const getColorsResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('Response schema for listing colors with pagination and metadata')

/**
 * Get a single color by ID
 */
export const getColorsIdParams = zod.object({
  "id": zod.uuid().describe('Color ID (UUID)')
})

export const getColorsIdResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format')

/**
 * Update a color
 */
export const patchColorsIdParams = zod.object({
  "id": zod.uuid().describe('Color ID (UUID)')
})

export const patchColorsIdBodyNameMax = 50;
export const patchColorsIdBodyEnNameMaxOne = 200;
export const patchColorsIdBodyDisplayNameMaxOne = 200;
export const patchColorsIdBodyHexRegExp = new RegExp('^#([0-9A-Fa-f]{3}){1,2}$');


export const patchColorsIdBody = zod.object({
  "name": zod.coerce.string().min(1).max(patchColorsIdBodyNameMax).optional().describe('Category name in native language'),
  "enName": zod.union([zod.coerce.string().max(patchColorsIdBodyEnNameMaxOne),zod.null()]).optional().describe('English name for internationalization'),
  "displayName": zod.union([zod.coerce.string().max(patchColorsIdBodyDisplayNameMaxOne),zod.null()]).optional().describe('for marketing. e.g: \'Snow white\''),
  "hex": zod.coerce.string().regex(patchColorsIdBodyHexRegExp).optional().describe('Hexadecimal color code (e.g., #FFFFFF, #FF5733)'),
  "isActive": zod.coerce.boolean().optional().describe('Filter by active status')
}).describe('Color update payload (any field optional)')

export const patchColorsIdResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format')

/**
 * Delete a color
 */
export const deleteColorsIdParams = zod.object({
  "id": zod.uuid().describe('Color ID (UUID)')
})

