/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttributeResponse,
  BaseResponse,
  ConflictError,
  CreateAttributeInput,
  ErrorResponse,
  GetAttributesParams,
  InternalError,
  ListAttributesResponse,
  NotfoundError,
  UpdateAttributeInput
} from '../../schemas';

import { axiosInstance } from '../../configs/axios-instance';




/**
 * Create a new attribute
 */
export const postAttributes = (
    createAttributeInput: CreateAttributeInput,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<AttributeResponse>(
      {url: `/attributes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAttributeInput, signal
    },
      );
    }
  


export const getPostAttributesMutationOptions = <TError = ErrorResponse | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAttributes>>, TError,{data: CreateAttributeInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAttributes>>, TError,{data: CreateAttributeInput}, TContext> => {

const mutationKey = ['postAttributes'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAttributes>>, {data: CreateAttributeInput}> = (props) => {
          const {data} = props ?? {};

          return  postAttributes(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAttributesMutationResult = NonNullable<Awaited<ReturnType<typeof postAttributes>>>
    export type PostAttributesMutationBody = CreateAttributeInput
    export type PostAttributesMutationError = ErrorResponse | ConflictError | InternalError

    export const usePostAttributes = <TError = ErrorResponse | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAttributes>>, TError,{data: CreateAttributeInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAttributes>>,
        TError,
        {data: CreateAttributeInput},
        TContext
      > => {

      const mutationOptions = getPostAttributesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * List all attributes with pagination and filters
 */
export const getAttributes = (
    params: GetAttributesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ListAttributesResponse>(
      {url: `/attributes`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetAttributesQueryKey = (params?: GetAttributesParams,) => {
    return [`/attributes`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAttributesQueryOptions = <TData = Awaited<ReturnType<typeof getAttributes>>, TError = InternalError>(params: GetAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttributesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttributes>>> = ({ signal }) => getAttributes(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttributes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttributesQueryResult = NonNullable<Awaited<ReturnType<typeof getAttributes>>>
export type GetAttributesQueryError = InternalError


export function useGetAttributes<TData = Awaited<ReturnType<typeof getAttributes>>, TError = InternalError>(
 params: GetAttributesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttributes>>,
          TError,
          Awaited<ReturnType<typeof getAttributes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttributes<TData = Awaited<ReturnType<typeof getAttributes>>, TError = InternalError>(
 params: GetAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttributes>>,
          TError,
          Awaited<ReturnType<typeof getAttributes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttributes<TData = Awaited<ReturnType<typeof getAttributes>>, TError = InternalError>(
 params: GetAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAttributes<TData = Awaited<ReturnType<typeof getAttributes>>, TError = InternalError>(
 params: GetAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAttributesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get a single attribute by ID
 */
export const getAttributesId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<AttributeResponse>(
      {url: `/attributes/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetAttributesIdQueryKey = (id?: string,) => {
    return [`/attributes/${id}`] as const;
    }

    
export const getGetAttributesIdQueryOptions = <TData = Awaited<ReturnType<typeof getAttributesId>>, TError = NotfoundError | InternalError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttributesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttributesId>>> = ({ signal }) => getAttributesId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttributesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttributesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAttributesId>>>
export type GetAttributesIdQueryError = NotfoundError | InternalError


export function useGetAttributesId<TData = Awaited<ReturnType<typeof getAttributesId>>, TError = NotfoundError | InternalError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttributesId>>,
          TError,
          Awaited<ReturnType<typeof getAttributesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttributesId<TData = Awaited<ReturnType<typeof getAttributesId>>, TError = NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttributesId>>,
          TError,
          Awaited<ReturnType<typeof getAttributesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttributesId<TData = Awaited<ReturnType<typeof getAttributesId>>, TError = NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAttributesId<TData = Awaited<ReturnType<typeof getAttributesId>>, TError = NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttributesId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAttributesIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update an attribute
 */
export const patchAttributesId = (
    id: string,
    updateAttributeInput: UpdateAttributeInput,
 ) => {
      
      
      return axiosInstance<AttributeResponse>(
      {url: `/attributes/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAttributeInput
    },
      );
    }
  


export const getPatchAttributesIdMutationOptions = <TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAttributesId>>, TError,{id: string;data: UpdateAttributeInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchAttributesId>>, TError,{id: string;data: UpdateAttributeInput}, TContext> => {

const mutationKey = ['patchAttributesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAttributesId>>, {id: string;data: UpdateAttributeInput}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAttributesId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAttributesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAttributesId>>>
    export type PatchAttributesIdMutationBody = UpdateAttributeInput
    export type PatchAttributesIdMutationError = ErrorResponse | NotfoundError | ConflictError | InternalError

    export const usePatchAttributesId = <TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAttributesId>>, TError,{id: string;data: UpdateAttributeInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAttributesId>>,
        TError,
        {id: string;data: UpdateAttributeInput},
        TContext
      > => {

      const mutationOptions = getPatchAttributesIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Delete an attribute
 */
export const deleteAttributesId = (
    id: string,
 ) => {
      
      
      return axiosInstance<BaseResponse>(
      {url: `/attributes/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteAttributesIdMutationOptions = <TError = NotfoundError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttributesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAttributesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAttributesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAttributesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAttributesId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAttributesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAttributesId>>>
    
    export type DeleteAttributesIdMutationError = NotfoundError | InternalError

    export const useDeleteAttributesId = <TError = NotfoundError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttributesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAttributesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAttributesIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    