/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  BrandResponse,
  ConflictError,
  CreateBrandInput,
  ErrorResponse,
  GetBrandsParams,
  InternalError,
  ListBrandResponse,
  NotfoundError,
  UpdateBrandInput,
} from "../../schemas";

import { axiosInstance } from "../../configs/axios-instance";

/**
 * Create a new brand
 */
export const postBrands = (
  createBrandInput: CreateBrandInput,
  signal?: AbortSignal,
) => {
  return axiosInstance<BrandResponse>({
    url: `/brands`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createBrandInput,
    signal,
  });
};

export const getPostBrandsMutationOptions = <
  TError = ErrorResponse | ConflictError | InternalError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBrands>>,
    TError,
    { data: CreateBrandInput },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBrands>>,
  TError,
  { data: CreateBrandInput },
  TContext
> => {
  const mutationKey = ["postBrands"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBrands>>,
    { data: CreateBrandInput }
  > = (props) => {
    const { data } = props ?? {};

    return postBrands(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBrandsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBrands>>
>;
export type PostBrandsMutationBody = CreateBrandInput;
export type PostBrandsMutationError =
  | ErrorResponse
  | ConflictError
  | InternalError;

export const usePostBrands = <
  TError = ErrorResponse | ConflictError | InternalError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBrands>>,
      TError,
      { data: CreateBrandInput },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBrands>>,
  TError,
  { data: CreateBrandInput },
  TContext
> => {
  const mutationOptions = getPostBrandsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all brands with pagination and filters
 */
export const getBrands = (params: GetBrandsParams, signal?: AbortSignal) => {
  return axiosInstance<ListBrandResponse>({
    url: `/brands`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetBrandsQueryKey = (params?: GetBrandsParams) => {
  return [`/brands`, ...(params ? [params] : [])] as const;
};

export const getGetBrandsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBrands>>,
  TError = InternalError,
>(
  params: GetBrandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrands>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBrandsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBrands>>> = ({
    signal,
  }) => getBrands(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBrands>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBrandsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBrands>>
>;
export type GetBrandsQueryError = InternalError;

export function useGetBrands<
  TData = Awaited<ReturnType<typeof getBrands>>,
  TError = InternalError,
>(
  params: GetBrandsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrands>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrands>>,
          TError,
          Awaited<ReturnType<typeof getBrands>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBrands<
  TData = Awaited<ReturnType<typeof getBrands>>,
  TError = InternalError,
>(
  params: GetBrandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrands>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrands>>,
          TError,
          Awaited<ReturnType<typeof getBrands>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBrands<
  TData = Awaited<ReturnType<typeof getBrands>>,
  TError = InternalError,
>(
  params: GetBrandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrands>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBrands<
  TData = Awaited<ReturnType<typeof getBrands>>,
  TError = InternalError,
>(
  params: GetBrandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrands>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBrandsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a single brand by ID
 */
export const getBrandsId = (id: string, signal?: AbortSignal) => {
  return axiosInstance<BrandResponse>({
    url: `/brands/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetBrandsIdQueryKey = (id?: string) => {
  return [`/brands/${id}`] as const;
};

export const getGetBrandsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getBrandsId>>,
  TError = ErrorResponse | NotfoundError | InternalError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBrandsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBrandsId>>> = ({
    signal,
  }) => getBrandsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBrandsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBrandsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBrandsId>>
>;
export type GetBrandsIdQueryError =
  | ErrorResponse
  | NotfoundError
  | InternalError;

export function useGetBrandsId<
  TData = Awaited<ReturnType<typeof getBrandsId>>,
  TError = ErrorResponse | NotfoundError | InternalError,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandsId>>,
          TError,
          Awaited<ReturnType<typeof getBrandsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBrandsId<
  TData = Awaited<ReturnType<typeof getBrandsId>>,
  TError = ErrorResponse | NotfoundError | InternalError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandsId>>,
          TError,
          Awaited<ReturnType<typeof getBrandsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBrandsId<
  TData = Awaited<ReturnType<typeof getBrandsId>>,
  TError = ErrorResponse | NotfoundError | InternalError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBrandsId<
  TData = Awaited<ReturnType<typeof getBrandsId>>,
  TError = ErrorResponse | NotfoundError | InternalError,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBrandsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a brand
 */
export const patchBrandsId = (
  id: string,
  updateBrandInput: UpdateBrandInput,
) => {
  return axiosInstance<BrandResponse>({
    url: `/brands/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateBrandInput,
  });
};

export const getPatchBrandsIdMutationOptions = <
  TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchBrandsId>>,
    TError,
    { id: string; data: UpdateBrandInput },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchBrandsId>>,
  TError,
  { id: string; data: UpdateBrandInput },
  TContext
> => {
  const mutationKey = ["patchBrandsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchBrandsId>>,
    { id: string; data: UpdateBrandInput }
  > = (props) => {
    const { id, data } = props ?? {};

    return patchBrandsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchBrandsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchBrandsId>>
>;
export type PatchBrandsIdMutationBody = UpdateBrandInput;
export type PatchBrandsIdMutationError =
  | ErrorResponse
  | NotfoundError
  | ConflictError
  | InternalError;

export const usePatchBrandsId = <
  TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchBrandsId>>,
      TError,
      { id: string; data: UpdateBrandInput },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchBrandsId>>,
  TError,
  { id: string; data: UpdateBrandInput },
  TContext
> => {
  const mutationOptions = getPatchBrandsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a brand
 */
export const deleteBrandsId = (id: string) => {
  return axiosInstance<BaseResponse>({
    url: `/brands/${id}`,
    method: "DELETE",
  });
};

export const getDeleteBrandsIdMutationOptions = <
  TError = ErrorResponse | NotfoundError | InternalError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBrandsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBrandsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteBrandsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBrandsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBrandsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBrandsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBrandsId>>
>;

export type DeleteBrandsIdMutationError =
  | ErrorResponse
  | NotfoundError
  | InternalError;

export const useDeleteBrandsId = <
  TError = ErrorResponse | NotfoundError | InternalError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBrandsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBrandsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteBrandsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
