/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { AttributeType } from "./attributeType";
import type { AttributeIconUrl } from "./attributeIconUrl";

/**
 * Product attribute entity
 */
export interface Attribute {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Attribute title
   * @minLength 2
   * @maxLength 50
   */
  title: string;
  /** Attribute type */
  type: AttributeType;
  /** URL to attribute icon */
  iconUrl?: AttributeIconUrl;
  /** Category ID this attribute belongs to */
  categoryId: string;
}
