/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { AttributeValue } from './attributeValue';

/**
 * Single attribute value response
 */
export type AttributeValueResponse = BaseResponse & {
  data?: AttributeValue;
};
