/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { Attribute } from "./attribute";

/**
 * Single attribute response
 */
export type AttributeResponse = BaseResponse & {
  data?: Attribute;
};
