/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponseSuccess } from "./baseResponseSuccess";

/**
 * Standard API response format
 */
export interface BaseResponse {
  /** Operation status */
  success?: BaseResponseSuccess;
}
