/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseErrorSuccess } from "./baseErrorSuccess";
import type { BaseErrorError } from "./baseErrorError";

/**
 * Standard API error format
 */
export interface BaseError {
  /** Operation status */
  success?: BaseErrorSuccess;
  /** Error message */
  error?: BaseErrorError;
}
