/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { Brand } from "./brand";

export type BrandResponse = BaseResponse & {
  data: Brand;
} & Required<
    Pick<
      BaseResponse & {
        data: Brand;
      },
      "data"
    >
  >;
