/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { Category } from "./category";

export type CategoryResponse = BaseResponse & {
  data: Category;
} & Required<
    Pick<
      BaseResponse & {
        data: Category;
      },
      "data"
    >
  >;
