/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * The scope of the search for this filter, providing context for filtering.
 */
export type CitiesResponseFiltersItemField = string | null;
