/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CityDeletedAt } from './cityDeletedAt';
import type { CityAbb } from './cityAbb';
import type { CityProvince } from './cityProvince';

/**
 * City entity with province reference
 */
export interface City {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: CityDeletedAt;
  /**
   * City name in native language
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** City abbreviation (e.g., THR for Tehran) */
  abb?: CityAbb;
  province: CityProvince;
}
