/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CityListResponseFiltersItemLabel } from "./cityListResponseFiltersItemLabel";
import type { CityListResponseFiltersItemUrl } from "./cityListResponseFiltersItemUrl";
import type { CityListResponseFiltersItemModel } from "./cityListResponseFiltersItemModel";
import type { CityListResponseFiltersItemField } from "./cityListResponseFiltersItemField";
import type { CityListResponseFiltersItemAdvanced } from "./cityListResponseFiltersItemAdvanced";
import type { CityListResponseFiltersItemEnumOptions } from "./cityListResponseFiltersItemEnumOptions";

export type CityListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: CityListResponseFiltersItemLabel;
  /** URL for the filter  */
  url?: CityListResponseFiltersItemUrl;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: CityListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: CityListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: CityListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: CityListResponseFiltersItemEnumOptions;
};
