/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { CityListResponseDetails } from "./cityListResponseDetails";
import type { CityListResponseFiltersItem } from "./cityListResponseFiltersItem";
import type { CityListResponseDataItem } from "./cityListResponseDataItem";

/**
 * Paginated list of cities
 */
export type CityListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: CityListResponseDetails;
  filters: CityListResponseFiltersItem[];
  data: CityListResponseDataItem[];
} & Required<
    Pick<
      BaseResponse & {
        /** Pagination metadata */
        details?: CityListResponseDetails;
        filters: CityListResponseFiltersItem[];
        data: CityListResponseDataItem[];
      },
      "filters" | "data"
    >
  >;
