/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CityListResponseDataItemDeletedAt } from "./cityListResponseDataItemDeletedAt";
import type { CityListResponseDataItemAbb } from "./cityListResponseDataItemAbb";
import type { CityListResponseDataItemProvince } from "./cityListResponseDataItemProvince";

export type CityListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: CityListResponseDataItemDeletedAt;
  /**
   * City name in native language
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** City abbreviation (e.g., THR for Tehran) */
  abb?: CityListResponseDataItemAbb;
  province: CityListResponseDataItemProvince;
  /** number of row in list table */
  rowNumber: number;
};
