/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { Color } from "./color";

export type ColorResponse = BaseResponse & {
  data: Color;
} & Required<
    Pick<
      BaseResponse & {
        data: Color;
      },
      "data"
    >
  >;
