/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { CountryListResponseDetails } from './countryListResponseDetails';
import type { CountryListResponseFiltersItem } from './countryListResponseFiltersItem';
import type { Country } from './country';

/**
 * Response for list country operations
 */
export type CountryListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: CountryListResponseDetails;
  filters: CountryListResponseFiltersItem[];
  /** Array of countries matching the query */
  data: Country[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: CountryListResponseDetails;
  filters: CountryListResponseFiltersItem[];
  /** Array of countries matching the query */
  data: Country[];
}, 'filters' | 'data'>>;
