/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CountryListResponseFiltersItemLabel } from './countryListResponseFiltersItemLabel';
import type { CountryListResponseFiltersItemModel } from './countryListResponseFiltersItemModel';
import type { CountryListResponseFiltersItemField } from './countryListResponseFiltersItemField';
import type { CountryListResponseFiltersItemAdvanced } from './countryListResponseFiltersItemAdvanced';
import type { CountryListResponseFiltersItemEnumOptions } from './countryListResponseFiltersItemEnumOptions';

export type CountryListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: CountryListResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: CountryListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: CountryListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: CountryListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: CountryListResponseFiltersItemEnumOptions;
};
