/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional Associated page ID
 */
export type CreateLabelInputPageId = string | null;
