/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInventoryInputGuaranteeId } from "./createInventoryInputGuaranteeId";
import type { CreateInventoryInputInsuranceId } from "./createInventoryInputInsuranceId";
import type { CreateInventoryInputLeasingId } from "./createInventoryInputLeasingId";
import type { CreateInventoryInputChequeId } from "./createInventoryInputChequeId";
import type { CreateInventoryInputCost } from "./createInventoryInputCost";
import type { CreateInventoryInputExpiryDate } from "./createInventoryInputExpiryDate";
import type { CreateInventoryInputWarehouseCode } from "./createInventoryInputWarehouseCode";
import type { CreateInventoryInputShelfCode } from "./createInventoryInputShelfCode";
import type { CreateInventoryInputHsCode } from "./createInventoryInputHsCode";
import type { CreateInventoryInputOriginCountry } from "./createInventoryInputOriginCountry";
import type { CreateInventoryInputPackageWeight } from "./createInventoryInputPackageWeight";
import type { CreateInventoryInputPackageDimensions } from "./createInventoryInputPackageDimensions";

/**
 * Inventory creation payload
 */
export interface CreateInventoryInput {
  /** Store ID */
  storeId: string;
  /** Location ID */
  locationId: string;
  /** Variant ID */
  variantId: string;
  /** Guarantee ID */
  guaranteeId?: CreateInventoryInputGuaranteeId;
  /** Insurance ID */
  insuranceId?: CreateInventoryInputInsuranceId;
  /** Leasing ID */
  leasingId?: CreateInventoryInputLeasingId;
  /** Cheque ID */
  chequeId?: CreateInventoryInputChequeId;
  /** Cost price */
  cost?: CreateInventoryInputCost;
  /** Base price */
  price: number;
  /**
   * Discount percentage
   * @minimum 0
   * @maximum 100
   */
  discountPercent: number;
  /** Price after discount (calculated) */
  discountPrice: number;
  /**
   * Current stock quantity
   * @minimum 0
   */
  inStock: number;
  /**
   * Low stock alert threshold
   * @minimum 0
   */
  lowStockThreshold: number;
  /** Expiry date for perishable items */
  expiryDate?: CreateInventoryInputExpiryDate;
  /** Warehouse code */
  warehouseCode?: CreateInventoryInputWarehouseCode;
  /** Shelf code for location in warehouse */
  shelfCode?: CreateInventoryInputShelfCode;
  /** Harmonized System code for customs */
  hsCode?: CreateInventoryInputHsCode;
  /** Country of manufacture/origin */
  originCountry?: CreateInventoryInputOriginCountry;
  /** Gross weight including packaging (kg) */
  packageWeight?: CreateInventoryInputPackageWeight;
  /** Packaged dimensions: length x width x height */
  packageDimensions?: CreateInventoryInputPackageDimensions;
}
