/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCategoryInputDesc } from "./createCategoryInputDesc";
import type { CreateCategoryInputIconUrl } from "./createCategoryInputIconUrl";
import type { CreateCategoryInputIsActive } from "./createCategoryInputIsActive";
import type { CreateCategoryInputParentId } from "./createCategoryInputParentId";
import type { CreateCategoryInputPromotionId } from "./createCategoryInputPromotionId";
import type { CreateCategoryInputShowInMenu } from "./createCategoryInputShowInMenu";

/**
 * Category creation payload
 */
export interface CreateCategoryInput {
  /**
   * Category name in native language
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * English name for internationalization
   * @minLength 2
   * @maxLength 50
   */
  enName: string;
  /** Parent category ID if exists */
  parentId?: CreateCategoryInputParentId;
  /** Unit ID */
  unitId: string;
  /** Filter by promotion ID */
  promotionId?: CreateCategoryInputPromotionId;
  /** Icon URL */
  iconUrl?: CreateCategoryInputIconUrl;
  /** Category description in native language */
  desc?: CreateCategoryInputDesc;
  /** Active status */
  isActive?: CreateCategoryInputIsActive;
  /** Show in menu status */
  showInMenu?: CreateCategoryInputShowInMenu;
}
