/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBrandInputEnName } from './createBrandInputEnName';
import type { CreateBrandInputLogoUrl } from './createBrandInputLogoUrl';
import type { CreateBrandInputWebsite } from './createBrandInputWebsite';
import type { CreateBrandInputDescription } from './createBrandInputDescription';

export interface CreateBrandInput {
  /**
   * Brand name in native language
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** English brand name */
  enName?: CreateBrandInputEnName;
  /** Logo image URL */
  logoUrl?: CreateBrandInputLogoUrl;
  /** Official website */
  website?: CreateBrandInputWebsite;
  /** Brand description */
  description?: CreateBrandInputDescription;
  /** Sorting priority */
  sortOrder: number;
  /** Filter by active status */
  isActive: boolean;
}
