/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProductInputMediasAnyOfItem } from './createProductInputMediasAnyOfItem';

/**
 * Product media
 */
export type CreateProductInputMedias = CreateProductInputMediasAnyOfItem[] | null;
