/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Country of manufacture/origin
 */
export type CreateInventoryInputOriginCountry = string | null;
