/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProvinceInputAbb } from "./createProvinceInputAbb";

/**
 * Province creation payload
 */
export interface CreateProvinceInput {
  /**
   * Province name in native language
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * Province abbreviation
   * @minLength 1
   * @maxLength 10
   */
  abb?: CreateProvinceInputAbb;
  /** Parent country ID */
  countryId: string;
}
