/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProductInputDescriptionsAnyOfItemMediaSide } from "./createProductInputDescriptionsAnyOfItemMediaSide";

export type CreateProductInputDescriptionsAnyOfItem = {
  id: string;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaSide: CreateProductInputDescriptionsAnyOfItemMediaSide;
  /** @nullable */
  mediaId: string | null;
};
