/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLocationInputStreetNumber } from "./createLocationInputStreetNumber";
import type { CreateLocationInputIsActive } from "./createLocationInputIsActive";

/**
 * Location creation payload
 */
export interface CreateLocationInput {
  /**
   * Street name
   * @minLength 1
   */
  street: string;
  /** Street number */
  streetNumber?: CreateLocationInputStreetNumber;
  /**
   * Postal/ZIP code
   * @minLength 3
   */
  postalCode: string;
  /** City ID */
  cityId: string;
  /** Whether the location is active */
  isActive?: CreateLocationInputIsActive;
}
