/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Media placement side
 */
export type CreateProductDescriptionInputMediaSide =
  (typeof CreateProductDescriptionInputMediaSide)[keyof typeof CreateProductDescriptionInputMediaSide];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProductDescriptionInputMediaSide = {
  LEFT: "LEFT",
  CENTER: "CENTER",
  RIGHT: "RIGHT",
} as const;
