/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInventoryInputPriceOverride } from "./createInventoryInputPriceOverride";
import type { CreateInventoryInputCostPriceOverride } from "./createInventoryInputCostPriceOverride";
import type { CreateInventoryInputBatchNumber } from "./createInventoryInputBatchNumber";
import type { CreateInventoryInputExpiryDate } from "./createInventoryInputExpiryDate";
import type { CreateInventoryInputWarehouseCode } from "./createInventoryInputWarehouseCode";
import type { CreateInventoryInputShelfCode } from "./createInventoryInputShelfCode";
import type { CreateInventoryInputLeadTimeDays } from "./createInventoryInputLeadTimeDays";
import type { CreateInventoryInputHsCode } from "./createInventoryInputHsCode";
import type { CreateInventoryInputOriginCountry } from "./createInventoryInputOriginCountry";
import type { CreateInventoryInputPackageWeight } from "./createInventoryInputPackageWeight";
import type { CreateInventoryInputPackageDimensions } from "./createInventoryInputPackageDimensions";

/**
 * Inventory creation payload
 */
export interface CreateInventoryInput {
  /** Store ID */
  storeId: string;
  /** Location ID */
  locationId: string;
  /** Variant ID */
  variantId: string;
  /** Base price */
  price: number;
  /** Override price for this inventory item */
  priceOverride?: CreateInventoryInputPriceOverride;
  /** Discount percentage */
  discount: number;
  /** Price after discount */
  discountPrice: number;
  /** Current stock quantity */
  inStock: number;
  /** Override cost price for this batch */
  costPriceOverride?: CreateInventoryInputCostPriceOverride;
  /** Batch number for tracking */
  batchNumber?: CreateInventoryInputBatchNumber;
  /** Expiry date for perishable items */
  expiryDate?: CreateInventoryInputExpiryDate;
  /** Warehouse code */
  warehouseCode?: CreateInventoryInputWarehouseCode;
  /** Shelf code for location in warehouse */
  shelfCode?: CreateInventoryInputShelfCode;
  /** Lead time in days to prepare for shipping */
  leadTimeDays?: CreateInventoryInputLeadTimeDays;
  /** Harmonized System code for customs */
  hsCode?: CreateInventoryInputHsCode;
  /** Country of manufacture/origin */
  originCountry?: CreateInventoryInputOriginCountry;
  /** Gross weight including packaging (kg) */
  packageWeight?: CreateInventoryInputPackageWeight;
  /** Packaged dimensions: length x width x height */
  packageDimensions?: CreateInventoryInputPackageDimensions;
  /** Low stock alert threshold */
  lowStockThreshold: number;
}
