/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Attribute value creation payload
 */
export interface CreateAttributeValueInput {
  /**
   * Attribute value
   * @minLength 1
   * @maxLength 100
   */
  value: string;
  /** Parent attribute ID */
  attributeId: string;
}
