/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for creating new measurement units
 */
export interface CreateUnitInput {
  /**
   * Unit title/name for measurement categorization
   * @minLength 2
   * @maxLength 100
   */
  title: string;
}
