/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateStoreInputLogo } from './createStoreInputLogo';
import type { CreateStoreInputDescription } from './createStoreInputDescription';
import type { CreateStoreInputEmail } from './createStoreInputEmail';
import type { CreateStoreInputPhone } from './createStoreInputPhone';
import type { CreateStoreInputWebsite } from './createStoreInputWebsite';
import type { CreateStoreInputOwnerId } from './createStoreInputOwnerId';

/**
 * Store creation payload
 */
export interface CreateStoreInput {
  /**
   * Store name (unique)
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * URL-friendly slug (unique, lowercase, hyphens only)
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-z0-9-]+$
   */
  slug: string;
  /** Store logo URL */
  logo?: CreateStoreInputLogo;
  /** Store description */
  description?: CreateStoreInputDescription;
  /** Business email (unique) */
  email?: CreateStoreInputEmail;
  /** Business phone (unique) */
  phone?: CreateStoreInputPhone;
  /** External website URL */
  website?: CreateStoreInputWebsite;
  /** Whether store is active */
  isActive: boolean;
  /** Platform approval status */
  isApproved: boolean;
  /** Owner user ID */
  ownerId?: CreateStoreInputOwnerId;
}
