/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLeasingInputDescription } from './createLeasingInputDescription';
import type { CreateLeasingInputCurrency } from './createLeasingInputCurrency';
import type { CreateLeasingInputIsActive } from './createLeasingInputIsActive';
import type { CreateLeasingInputBankId } from './createLeasingInputBankId';
import type { CreateLeasingInputCurrencyId } from './createLeasingInputCurrencyId';
import type { CreateLeasingInputContractTemplateUrl } from './createLeasingInputContractTemplateUrl';
import type { CreateLeasingInputTotalLeaseAmount } from './createLeasingInputTotalLeaseAmount';
import type { CreateLeasingInputAccountingRefId } from './createLeasingInputAccountingRefId';
import type { CreateLeasingInputIsRegisteredWithTax } from './createLeasingInputIsRegisteredWithTax';

/**
 * Product leasing plan for B2B/B2C
 */
export interface CreateLeasingInput {
  /**
   * Leasing plan title
   * @minLength 2
   * @maxLength 200
   */
  title: string;
  /** Detailed description of leasing terms */
  description?: CreateLeasingInputDescription;
  /**
   * Duration in months
   * @minimum 1
   */
  months: number;
  /**
   * Name of the leasing provider (bank / FinTech)
   * @minLength 1
   * @maxLength 120
   */
  providerName: string;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  firstPaymentPercent: number;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  sellerLeasingProfit: number;
  /** Currency code */
  currency?: CreateLeasingInputCurrency;
  /** Is this leasing plan active? */
  isActive?: CreateLeasingInputIsActive;
  /** Display priority (descending) */
  sortOrder: number;
  /** Associated bank ID */
  bankId?: CreateLeasingInputBankId;
  /** Associated currency ID */
  currencyId?: CreateLeasingInputCurrencyId;
  /** URL to lease contract template */
  contractTemplateUrl?: CreateLeasingInputContractTemplateUrl;
  /** Total lease amount (including all payments) */
  totalLeaseAmount?: CreateLeasingInputTotalLeaseAmount;
  /** External accounting system reference ID */
  accountingRefId?: CreateLeasingInputAccountingRefId;
  /** Registered with tax authority? */
  isRegisteredWithTax?: CreateLeasingInputIsRegisteredWithTax;
}
