/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional ID referencing a ProductMedia entity
 */
export type CreateProductDescriptionInputMediaId = string | null;
