/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCityInputAbb } from './createCityInputAbb';

/**
 * City entity with province reference
 */
export interface CreateCityInput {
  /**
   * City name in native language
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** City abbreviation (e.g., THR for Tehran) */
  abb?: CreateCityInputAbb;
  /** Associated province ID */
  provinceId: string;
}
