/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateProductInputDescriptionsAnyOfItemMediaSide =
  | (typeof CreateProductInputDescriptionsAnyOfItemMediaSide)[keyof typeof CreateProductInputDescriptionsAnyOfItemMediaSide]
  | null;

export const CreateProductInputDescriptionsAnyOfItemMediaSide = {
  LEFT: "LEFT",
  CENTER: "CENTER",
  RIGHT: "RIGHT",
} as const;
