/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProductDescriptionInputMediaSide } from './createProductDescriptionInputMediaSide';
import type { CreateProductDescriptionInputMediaId } from './createProductDescriptionInputMediaId';

/**
 * Create new product description section
 */
export interface CreateProductDescriptionInput {
  /**
   * Description section title
   * @minLength 2
   * @maxLength 100
   */
  title: string;
  /**
   * Detailed description content
   * @minLength 2
   * @maxLength 2000
   */
  text: string;
  /** Media placement side */
  mediaSide: CreateProductDescriptionInputMediaSide;
  /** Optional ID referencing a ProductMedia entity */
  mediaId?: CreateProductDescriptionInputMediaId;
  /** Associated product ID */
  productId: string;
}
