/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAttributeInputType } from './createAttributeInputType';
import type { CreateAttributeInputIconUrl } from './createAttributeInputIconUrl';

/**
 * Attribute creation payload
 */
export interface CreateAttributeInput {
  /**
   * Attribute title
   * @minLength 2
   * @maxLength 50
   */
  title: string;
  /** Attribute type */
  type: CreateAttributeInputType;
  /** URL to attribute icon */
  iconUrl?: CreateAttributeInputIconUrl;
  /** Category ID this attribute belongs to */
  categoryId: string;
}
