/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLabelInputPageId } from "./createLabelInputPageId";

/**
 * Label creation payload
 */
export interface CreateLabelInput {
  /**
   * Label name
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /** Optional Associated page ID */
  pageId?: CreateLabelInputPageId;
}
