/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Country creation payload
 */
export interface CreateCountryInput {
  /**
   * Country name in native language
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * ISO 3166-1 alpha-2 country code
   * @minLength 2
   * @maxLength 2
   * @pattern ^[A-Z]{2}$
   */
  isoCode: string;
  /**
   * International telephone prefix
   * @minLength 2
   * @maxLength 5
   * @pattern ^\+\d{1,4}$
   */
  phoneCode: string;
}
