/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAttributeValueInputValue } from './createAttributeValueInputValue';
import type { CreateAttributeValueInputAttributeId } from './createAttributeValueInputAttributeId';
import type { CreateAttributeValueInputVariantId } from './createAttributeValueInputVariantId';

/**
 * Attribute value creation payload
 */
export interface CreateAttributeValueInput {
  /** Filter by value content */
  value?: CreateAttributeValueInputValue;
  /** Filter by attribute ID */
  attributeId?: CreateAttributeValueInputAttributeId;
  /** Filter by variant ID */
  variantId?: CreateAttributeValueInputVariantId;
}
