/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { CurrencyListResponseDetails } from './currencyListResponseDetails';
import type { CurrencyListResponseFiltersItem } from './currencyListResponseFiltersItem';
import type { CurrencyListResponseDataItem } from './currencyListResponseDataItem';

/**
 * Paginated list of currencies
 */
export type CurrencyListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: CurrencyListResponseDetails;
  filters: CurrencyListResponseFiltersItem[];
  data: CurrencyListResponseDataItem[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: CurrencyListResponseDetails;
  filters: CurrencyListResponseFiltersItem[];
  data: CurrencyListResponseDataItem[];
}, 'filters' | 'data'>>;
