/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyListResponseFiltersItemLabel } from "./currencyListResponseFiltersItemLabel";
import type { CurrencyListResponseFiltersItemModel } from "./currencyListResponseFiltersItemModel";
import type { CurrencyListResponseFiltersItemField } from "./currencyListResponseFiltersItemField";
import type { CurrencyListResponseFiltersItemAdvanced } from "./currencyListResponseFiltersItemAdvanced";
import type { CurrencyListResponseFiltersItemEnumOptions } from "./currencyListResponseFiltersItemEnumOptions";

export type CurrencyListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: CurrencyListResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: CurrencyListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: CurrencyListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: CurrencyListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: CurrencyListResponseFiltersItemEnumOptions;
};
