/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyListResponseDataItemDeletedAt } from "./currencyListResponseDataItemDeletedAt";

export type CurrencyListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: CurrencyListResponseDataItemDeletedAt;
  /**
   * Currency name
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * Currency symbol
   * @minLength 1
   * @maxLength 10
   */
  symbol: string;
  /** Is this the default currency? */
  isDefault: boolean;
  /** number of row in list table */
  rowNumber: number;
};
