/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyDeletedAt } from "./currencyDeletedAt";

/**
 * Currency entity for pricing
 */
export interface Currency {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: CurrencyDeletedAt;
  /**
   * Currency name
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * Currency symbol
   * @minLength 1
   * @maxLength 10
   */
  symbol: string;
  /** Is this the default currency? */
  isDefault: boolean;
}
