/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

export type GetAttributeValuesType =
  (typeof GetAttributeValuesType)[keyof typeof GetAttributeValuesType];

export const GetAttributeValuesType = {
  text: "text",
  number: "number",
  boolean: "boolean",
  date: "date",
} as const;
