/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

export type GetCitiesParams = {
  /**
   * Number of records to skip
   * @minimum 0
   */
  skip: number;
  /**
   * Maximum number of records to return
   * @minimum 1
   * @maximum 20
   */
  limit: number;
  provinceId?: string | null;
  /**
   * Search term for city name
   */
  search?: string | null;
};
