/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

export type GetGuaranteesParams = {
  /**
   * Field to sort by
   */
  field?: string | null;
  /**
   * Sort order
   */
  order?: "asc" | "desc" | null;
  /**
   * Number of records to skip
   * @minimum 0
   */
  skip: number;
  /**
   * Maximum number of records to return
   * @minimum 1
   * @maximum 20
   */
  limit: number;
  /**
   * Optional date input, usually null
   */
  deletedAt?: string | null;
  /**
   * Filter by guarantee title
   */
  title?: string | null;
  /**
   * Filter by provider name
   */
  providerName?: string | null;
  /**
   * Filter by provider code
   */
  providerCode?: string | null;
  /**
   * Filter by active status
   */
  isActive?: boolean | null;
  /**
   * Filter by international status
   */
  isInternational?: boolean | null;
};
