/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LocationType } from "./locationType";

export type GetStoreLocationsWarehouseStoreIdParams = {
  /**
   * Field to sort by
   */
  field?: string | null;
  /**
   * Sort order
   */
  order?: "asc" | "desc" | null;
  /**
   * Number of records to skip
   * @minimum 0
   */
  skip: number;
  /**
   * Maximum number of records to return
   * @minimum 1
   * @maximum 20
   */
  limit: number;
  /**
   * Filter by location type
   */
  type?: LocationType;
};
