/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { GetUnits200FiltersItemLabel } from "./getUnits200FiltersItemLabel";
import type { GetUnits200FiltersItemModel } from "./getUnits200FiltersItemModel";
import type { GetUnits200FiltersItemField } from "./getUnits200FiltersItemField";
import type { GetUnits200FiltersItemAdvanced } from "./getUnits200FiltersItemAdvanced";
import type { GetUnits200FiltersItemEnumOptions } from "./getUnits200FiltersItemEnumOptions";

export type GetUnits200FiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: GetUnits200FiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: GetUnits200FiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: GetUnits200FiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: GetUnits200FiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: GetUnits200FiltersItemEnumOptions;
};
