/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { GetUnits200DataItemDeletedAt } from './getUnits200DataItemDeletedAt';

export type GetUnits200DataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: GetUnits200DataItemDeletedAt;
  /**
   * Unit title/name for measurement categorization
   * @minLength 2
   * @maxLength 100
   */
  title: string;
  /** number of row in list table */
  rowNumber: number;
};
