/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Currency ID of guarantee price
 */
export type GuaranteeListResponseDataItemCurrencyId = string | null;
