/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { GuaranteeListResponseFiltersItemLabel } from './guaranteeListResponseFiltersItemLabel';
import type { GuaranteeListResponseFiltersItemUrl } from './guaranteeListResponseFiltersItemUrl';
import type { GuaranteeListResponseFiltersItemModel } from './guaranteeListResponseFiltersItemModel';
import type { GuaranteeListResponseFiltersItemField } from './guaranteeListResponseFiltersItemField';
import type { GuaranteeListResponseFiltersItemAdvanced } from './guaranteeListResponseFiltersItemAdvanced';
import type { GuaranteeListResponseFiltersItemEnumOptions } from './guaranteeListResponseFiltersItemEnumOptions';

export type GuaranteeListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: GuaranteeListResponseFiltersItemLabel;
  /** URL for the filter  */
  url?: GuaranteeListResponseFiltersItemUrl;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: GuaranteeListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: GuaranteeListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: GuaranteeListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: GuaranteeListResponseFiltersItemEnumOptions;
};
