/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { GuaranteeDeletedAt } from './guaranteeDeletedAt';
import type { GuaranteeStart } from './guaranteeStart';
import type { GuaranteeMonths } from './guaranteeMonths';
import type { GuaranteeDays } from './guaranteeDays';
import type { GuaranteeLogo } from './guaranteeLogo';
import type { GuaranteeProviderName } from './guaranteeProviderName';
import type { GuaranteeProviderAddress } from './guaranteeProviderAddress';
import type { GuaranteeProviderPhone } from './guaranteeProviderPhone';
import type { GuaranteeProviderCode } from './guaranteeProviderCode';
import type { GuaranteeTermsUrl } from './guaranteeTermsUrl';
import type { GuaranteeClaimProcess } from './guaranteeClaimProcess';
import type { GuaranteeResponseTime } from './guaranteeResponseTime';
import type { GuaranteeSepidarGuaranteeId } from './guaranteeSepidarGuaranteeId';

/**
 * Product warranty/guarantee entity
 */
export interface Guarantee {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: GuaranteeDeletedAt;
  /**
   * Guarantee title displayed to customer
   * @minLength 2
   * @maxLength 200
   */
  title: string;
  /** Start date of guarantee validity */
  start?: GuaranteeStart;
  /** Duration in months (optional — use with days) */
  months?: GuaranteeMonths;
  /** Duration in days (optional — use with months) */
  days?: GuaranteeDays;
  /** Logo URL of guarantee provider */
  logo?: GuaranteeLogo;
  /** Name of warranty provider */
  providerName?: GuaranteeProviderName;
  /** Physical address of provider */
  providerAddress?: GuaranteeProviderAddress;
  /** Contact phone of provider */
  providerPhone?: GuaranteeProviderPhone;
  /** Internal provider code */
  providerCode?: GuaranteeProviderCode;
  /** URL to full terms and conditions */
  termsUrl?: GuaranteeTermsUrl;
  /** Can be claimed internationally? */
  isInternational: boolean;
  /** How to claim this guarantee */
  claimProcess?: GuaranteeClaimProcess;
  /** Max days to respond to claim */
  responseTime?: GuaranteeResponseTime;
  /** Is this guarantee active for new sales? */
  isActive: boolean;
  /** Display order priority */
  sortOrder: number;
  /** Sepidar system reference ID */
  sepidarGuaranteeId?: GuaranteeSepidarGuaranteeId;
  /** Is this guarantee registered with tax authority? */
  isRegisteredWithTax: boolean;
}
