/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { GuaranteeListResponseDataItemDeletedAt } from './guaranteeListResponseDataItemDeletedAt';
import type { GuaranteeListResponseDataItemStart } from './guaranteeListResponseDataItemStart';
import type { GuaranteeListResponseDataItemMonths } from './guaranteeListResponseDataItemMonths';
import type { GuaranteeListResponseDataItemDays } from './guaranteeListResponseDataItemDays';
import type { GuaranteeListResponseDataItemLogo } from './guaranteeListResponseDataItemLogo';
import type { GuaranteeListResponseDataItemProviderName } from './guaranteeListResponseDataItemProviderName';
import type { GuaranteeListResponseDataItemProviderAddress } from './guaranteeListResponseDataItemProviderAddress';
import type { GuaranteeListResponseDataItemProviderPhone } from './guaranteeListResponseDataItemProviderPhone';
import type { GuaranteeListResponseDataItemProviderCode } from './guaranteeListResponseDataItemProviderCode';
import type { GuaranteeListResponseDataItemTermsUrl } from './guaranteeListResponseDataItemTermsUrl';
import type { GuaranteeListResponseDataItemClaimProcess } from './guaranteeListResponseDataItemClaimProcess';
import type { GuaranteeListResponseDataItemResponseTime } from './guaranteeListResponseDataItemResponseTime';
import type { GuaranteeListResponseDataItemSepidarGuaranteeId } from './guaranteeListResponseDataItemSepidarGuaranteeId';

export type GuaranteeListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: GuaranteeListResponseDataItemDeletedAt;
  /**
   * Guarantee title displayed to customer
   * @minLength 2
   * @maxLength 200
   */
  title: string;
  /** Start date of guarantee validity */
  start?: GuaranteeListResponseDataItemStart;
  /** Duration in months (optional — use with days) */
  months?: GuaranteeListResponseDataItemMonths;
  /** Duration in days (optional — use with months) */
  days?: GuaranteeListResponseDataItemDays;
  /** Logo URL of guarantee provider */
  logo?: GuaranteeListResponseDataItemLogo;
  /** Name of warranty provider */
  providerName?: GuaranteeListResponseDataItemProviderName;
  /** Physical address of provider */
  providerAddress?: GuaranteeListResponseDataItemProviderAddress;
  /** Contact phone of provider */
  providerPhone?: GuaranteeListResponseDataItemProviderPhone;
  /** Internal provider code */
  providerCode?: GuaranteeListResponseDataItemProviderCode;
  /** URL to full terms and conditions */
  termsUrl?: GuaranteeListResponseDataItemTermsUrl;
  /** Can be claimed internationally? */
  isInternational: boolean;
  /** How to claim this guarantee */
  claimProcess?: GuaranteeListResponseDataItemClaimProcess;
  /** Max days to respond to claim */
  responseTime?: GuaranteeListResponseDataItemResponseTime;
  /** Is this guarantee active for new sales? */
  isActive: boolean;
  /** Display order priority */
  sortOrder: number;
  /** Sepidar system reference ID */
  sepidarGuaranteeId?: GuaranteeListResponseDataItemSepidarGuaranteeId;
  /** Is this guarantee registered with tax authority? */
  isRegisteredWithTax: boolean;
  /** number of row in list table */
  rowNumber: number;
};
