/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { InsuranceListResponseDataItemDeletedAt } from "./insuranceListResponseDataItemDeletedAt";
import type { InsuranceListResponseDataItemStart } from "./insuranceListResponseDataItemStart";
import type { InsuranceListResponseDataItemMonths } from "./insuranceListResponseDataItemMonths";
import type { InsuranceListResponseDataItemDays } from "./insuranceListResponseDataItemDays";
import type { InsuranceListResponseDataItemLogo } from "./insuranceListResponseDataItemLogo";
import type { InsuranceListResponseDataItemProviderName } from "./insuranceListResponseDataItemProviderName";
import type { InsuranceListResponseDataItemCoverage } from "./insuranceListResponseDataItemCoverage";
import type { InsuranceListResponseDataItemExclusions } from "./insuranceListResponseDataItemExclusions";
import type { InsuranceListResponseDataItemClaimLimit } from "./insuranceListResponseDataItemClaimLimit";
import type { InsuranceListResponseDataItemDeductible } from "./insuranceListResponseDataItemDeductible";
import type { InsuranceListResponseDataItemClaimProcess } from "./insuranceListResponseDataItemClaimProcess";
import type { InsuranceListResponseDataItemMinOrderValue } from "./insuranceListResponseDataItemMinOrderValue";
import type { InsuranceListResponseDataItemMaxOrderValue } from "./insuranceListResponseDataItemMaxOrderValue";

export type InsuranceListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: InsuranceListResponseDataItemDeletedAt;
  /**
   * Insurance title displayed to customer
   * @minLength 2
   * @maxLength 200
   */
  title: string;
  /** Coverage start date */
  start?: InsuranceListResponseDataItemStart;
  /** Duration in months (optional) */
  months?: InsuranceListResponseDataItemMonths;
  days?: InsuranceListResponseDataItemDays;
  /** Provider logo URL */
  logo?: InsuranceListResponseDataItemLogo;
  /**
   * Cost to buyer (in IRR or USD)
   * @minimum 0
   */
  price: number;
  /** Insurance provider name */
  providerName?: InsuranceListResponseDataItemProviderName;
  /** What's covered */
  coverage?: InsuranceListResponseDataItemCoverage;
  /** What's NOT covered */
  exclusions?: InsuranceListResponseDataItemExclusions;
  /** Maximum claim amount per incident */
  claimLimit?: InsuranceListResponseDataItemClaimLimit;
  /** Buyer pays first amount (deductible) */
  deductible?: InsuranceListResponseDataItemDeductible;
  /** How to file a claim */
  claimProcess?: InsuranceListResponseDataItemClaimProcess;
  /** Is this insurance active for new sales? */
  isActive: boolean;
  /** Minimum order value to qualify */
  minOrderValue?: InsuranceListResponseDataItemMinOrderValue;
  /** Maximum order value allowed */
  maxOrderValue?: InsuranceListResponseDataItemMaxOrderValue;
  /** Display order priority */
  sortOrder: number;
  /** number of row in list table */
  rowNumber: number;
};
