/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Maximum claim amount per incident
 */
export type InsuranceListResponseDataItemClaimLimit = number | null;
