/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseError } from './baseError';

export type InternalError = BaseError & {
  /** Error code */
  code: string;
  /** Error detials */
  details?: unknown;
} & Required<Pick<BaseError & {
  /** Error code */
  code: string;
  /** Error detials */
  details?: unknown;
}, 'code'>>;
