/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { InventoryGuaranteeId } from './inventoryGuaranteeId';
import type { InventoryInsuranceId } from './inventoryInsuranceId';
import type { InventoryLeasingId } from './inventoryLeasingId';
import type { InventoryChequeId } from './inventoryChequeId';
import type { InventoryCost } from './inventoryCost';
import type { InventoryExpiryDate } from './inventoryExpiryDate';
import type { InventoryWarehouseCode } from './inventoryWarehouseCode';
import type { InventoryShelfCode } from './inventoryShelfCode';
import type { InventoryHsCode } from './inventoryHsCode';
import type { InventoryOriginCountry } from './inventoryOriginCountry';
import type { InventoryPackageWeight } from './inventoryPackageWeight';
import type { InventoryPackageDimensions } from './inventoryPackageDimensions';

/**
 * Inventory item representing stock at a specific location
 */
export interface Inventory {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Store ID */
  storeId: string;
  /** Location ID */
  locationId: string;
  /** Variant ID */
  variantId: string;
  /** Guarantee ID */
  guaranteeId?: InventoryGuaranteeId;
  /** Insurance ID */
  insuranceId?: InventoryInsuranceId;
  /** Leasing ID */
  leasingId?: InventoryLeasingId;
  /** Cheque ID */
  chequeId?: InventoryChequeId;
  /** Cost price */
  cost?: InventoryCost;
  /** Base price */
  price: number;
  /**
   * Discount percentage
   * @minimum 0
   * @maximum 100
   */
  discountPercent: number;
  /** Price after discount (calculated) */
  discountPrice: number;
  /**
   * Current stock quantity
   * @minimum 0
   */
  inStock: number;
  /**
   * Total sold quantity
   * @minimum 0
   */
  sold: number;
  /**
   * Average rating
   * @minimum 0
   * @maximum 5
   */
  rate: number;
  /**
   * Low stock alert threshold
   * @minimum 0
   */
  lowStockThreshold: number;
  /** Expiry date for perishable items */
  expiryDate?: InventoryExpiryDate;
  /** Warehouse code */
  warehouseCode?: InventoryWarehouseCode;
  /** Shelf code for location in warehouse */
  shelfCode?: InventoryShelfCode;
  /** Harmonized System code for customs */
  hsCode?: InventoryHsCode;
  /** Country of manufacture/origin */
  originCountry?: InventoryOriginCountry;
  /** Gross weight including packaging (kg) */
  packageWeight?: InventoryPackageWeight;
  /** Packaged dimensions: length x width x height */
  packageDimensions?: InventoryPackageDimensions;
}
