/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LabelPageId } from './labelPageId';

/**
 * Label entity for fast search of homepage products
 */
export interface Label {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Label name
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /** Optional Associated page ID */
  pageId?: LabelPageId;
}
