/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { LabelListResponseDetails } from "./labelListResponseDetails";
import type { LabelListResponseFiltersItem } from "./labelListResponseFiltersItem";
import type { Label } from "./label";

export type LabelListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: LabelListResponseDetails;
  filters: LabelListResponseFiltersItem[];
  /** Array of labels matching the query */
  data: Label[];
} & Required<
    Pick<
      BaseResponse & {
        /** Pagination metadata */
        details?: LabelListResponseDetails;
        filters: LabelListResponseFiltersItem[];
        /** Array of labels matching the query */
        data: Label[];
      },
      "filters" | "data"
    >
  >;
