/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LabelListResponseFiltersItemLabel } from "./labelListResponseFiltersItemLabel";
import type { LabelListResponseFiltersItemModel } from "./labelListResponseFiltersItemModel";
import type { LabelListResponseFiltersItemField } from "./labelListResponseFiltersItemField";
import type { LabelListResponseFiltersItemAdvanced } from "./labelListResponseFiltersItemAdvanced";
import type { LabelListResponseFiltersItemEnumOptions } from "./labelListResponseFiltersItemEnumOptions";

export type LabelListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: LabelListResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: LabelListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: LabelListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: LabelListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: LabelListResponseFiltersItemEnumOptions;
};
