/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LeasingListResponseFiltersItemLabel } from "./leasingListResponseFiltersItemLabel";
import type { LeasingListResponseFiltersItemUrl } from "./leasingListResponseFiltersItemUrl";
import type { LeasingListResponseFiltersItemModel } from "./leasingListResponseFiltersItemModel";
import type { LeasingListResponseFiltersItemField } from "./leasingListResponseFiltersItemField";
import type { LeasingListResponseFiltersItemAdvanced } from "./leasingListResponseFiltersItemAdvanced";
import type { LeasingListResponseFiltersItemEnumOptions } from "./leasingListResponseFiltersItemEnumOptions";

export type LeasingListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: LeasingListResponseFiltersItemLabel;
  /** URL for the filter  */
  url?: LeasingListResponseFiltersItemUrl;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: LeasingListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: LeasingListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: LeasingListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: LeasingListResponseFiltersItemEnumOptions;
};
