/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Detailed description of leasing terms
 */
export type LeasingListResponseDataItemDescription = string | null;
