/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { LeasingListResponseDetails } from "./leasingListResponseDetails";
import type { LeasingListResponseFiltersItem } from "./leasingListResponseFiltersItem";
import type { LeasingListResponseDataItem } from "./leasingListResponseDataItem";

/**
 * Paginated list of leasing plans
 */
export type LeasingListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: LeasingListResponseDetails;
  filters: LeasingListResponseFiltersItem[];
  data: LeasingListResponseDataItem[];
} & Required<
    Pick<
      BaseResponse & {
        /** Pagination metadata */
        details?: LeasingListResponseDetails;
        filters: LeasingListResponseFiltersItem[];
        data: LeasingListResponseDataItem[];
      },
      "filters" | "data"
    >
  >;
