/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Total lease amount (including all payments)
 */
export type LeasingListResponseDataItemTotalLeaseAmount = number | null;
