/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LeasingDeletedAt } from './leasingDeletedAt';
import type { LeasingDescription } from './leasingDescription';
import type { LeasingCurrency } from './leasingCurrency';
import type { LeasingIsActive } from './leasingIsActive';
import type { LeasingBankId } from './leasingBankId';
import type { LeasingCurrencyId } from './leasingCurrencyId';
import type { LeasingContractTemplateUrl } from './leasingContractTemplateUrl';
import type { LeasingTotalLeaseAmount } from './leasingTotalLeaseAmount';
import type { LeasingAccountingRefId } from './leasingAccountingRefId';
import type { LeasingIsRegisteredWithTax } from './leasingIsRegisteredWithTax';

/**
 * Product leasing plan for B2B/B2C
 */
export interface Leasing {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: LeasingDeletedAt;
  /**
   * Leasing plan title
   * @minLength 2
   * @maxLength 200
   */
  title: string;
  /** Detailed description of leasing terms */
  description?: LeasingDescription;
  /**
   * Duration in months
   * @minimum 1
   */
  months: number;
  /**
   * Name of the leasing provider (bank / FinTech)
   * @minLength 1
   * @maxLength 120
   */
  providerName: string;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  firstPaymentPercent: number;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  sellerLeasingProfit: number;
  /** Currency code */
  currency?: LeasingCurrency;
  /** Is this leasing plan active? */
  isActive: LeasingIsActive;
  /** Display priority (descending) */
  sortOrder: number;
  /** Associated bank ID */
  bankId?: LeasingBankId;
  /** Associated currency ID */
  currencyId?: LeasingCurrencyId;
  /** URL to lease contract template */
  contractTemplateUrl?: LeasingContractTemplateUrl;
  /** Total lease amount (including all payments) */
  totalLeaseAmount?: LeasingTotalLeaseAmount;
  /** External accounting system reference ID */
  accountingRefId?: LeasingAccountingRefId;
  /** Registered with tax authority? */
  isRegisteredWithTax?: LeasingIsRegisteredWithTax;
}
