/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LeasingListResponseDataItemDeletedAt } from './leasingListResponseDataItemDeletedAt';
import type { LeasingListResponseDataItemDescription } from './leasingListResponseDataItemDescription';
import type { LeasingListResponseDataItemCurrency } from './leasingListResponseDataItemCurrency';
import type { LeasingListResponseDataItemIsActive } from './leasingListResponseDataItemIsActive';
import type { LeasingListResponseDataItemBankId } from './leasingListResponseDataItemBankId';
import type { LeasingListResponseDataItemCurrencyId } from './leasingListResponseDataItemCurrencyId';
import type { LeasingListResponseDataItemContractTemplateUrl } from './leasingListResponseDataItemContractTemplateUrl';
import type { LeasingListResponseDataItemTotalLeaseAmount } from './leasingListResponseDataItemTotalLeaseAmount';
import type { LeasingListResponseDataItemAccountingRefId } from './leasingListResponseDataItemAccountingRefId';
import type { LeasingListResponseDataItemIsRegisteredWithTax } from './leasingListResponseDataItemIsRegisteredWithTax';

export type LeasingListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: LeasingListResponseDataItemDeletedAt;
  /**
   * Leasing plan title
   * @minLength 2
   * @maxLength 200
   */
  title: string;
  /** Detailed description of leasing terms */
  description?: LeasingListResponseDataItemDescription;
  /**
   * Duration in months
   * @minimum 1
   */
  months: number;
  /**
   * Name of the leasing provider (bank / FinTech)
   * @minLength 1
   * @maxLength 120
   */
  providerName: string;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  firstPaymentPercent: number;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  sellerLeasingProfit: number;
  /** Currency code */
  currency?: LeasingListResponseDataItemCurrency;
  /** Is this leasing plan active? */
  isActive: LeasingListResponseDataItemIsActive;
  /** Display priority (descending) */
  sortOrder: number;
  /** Associated bank ID */
  bankId?: LeasingListResponseDataItemBankId;
  /** Associated currency ID */
  currencyId?: LeasingListResponseDataItemCurrencyId;
  /** URL to lease contract template */
  contractTemplateUrl?: LeasingListResponseDataItemContractTemplateUrl;
  /** Total lease amount (including all payments) */
  totalLeaseAmount?: LeasingListResponseDataItemTotalLeaseAmount;
  /** External accounting system reference ID */
  accountingRefId?: LeasingListResponseDataItemAccountingRefId;
  /** Registered with tax authority? */
  isRegisteredWithTax?: LeasingListResponseDataItemIsRegisteredWithTax;
  /** number of row in list table */
  rowNumber: number;
};
