/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { Leasing } from "./leasing";

/**
 * Response for single leasing operations
 */
export type LeasingResponse = BaseResponse & {
  data: Leasing;
} & Required<
    Pick<
      BaseResponse & {
        data: Leasing;
      },
      "data"
    >
  >;
