/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListInventoriesResponseDataItemDeletedAt } from './listInventoriesResponseDataItemDeletedAt';
import type { ListInventoriesResponseDataItemPriceOverride } from './listInventoriesResponseDataItemPriceOverride';
import type { ListInventoriesResponseDataItemCostPriceOverride } from './listInventoriesResponseDataItemCostPriceOverride';
import type { ListInventoriesResponseDataItemBatchNumber } from './listInventoriesResponseDataItemBatchNumber';
import type { ListInventoriesResponseDataItemExpiryDate } from './listInventoriesResponseDataItemExpiryDate';
import type { ListInventoriesResponseDataItemWarehouseCode } from './listInventoriesResponseDataItemWarehouseCode';
import type { ListInventoriesResponseDataItemShelfCode } from './listInventoriesResponseDataItemShelfCode';
import type { ListInventoriesResponseDataItemLeadTimeDays } from './listInventoriesResponseDataItemLeadTimeDays';
import type { ListInventoriesResponseDataItemHsCode } from './listInventoriesResponseDataItemHsCode';
import type { ListInventoriesResponseDataItemOriginCountry } from './listInventoriesResponseDataItemOriginCountry';
import type { ListInventoriesResponseDataItemPackageWeight } from './listInventoriesResponseDataItemPackageWeight';
import type { ListInventoriesResponseDataItemPackageDimensions } from './listInventoriesResponseDataItemPackageDimensions';

export type ListInventoriesResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: ListInventoriesResponseDataItemDeletedAt;
  /** Store ID */
  storeId: string;
  /** Location ID */
  locationId: string;
  /** Variant ID */
  variantId: string;
  /** Base price */
  price: number;
  /** Override price for this inventory item */
  priceOverride?: ListInventoriesResponseDataItemPriceOverride;
  /** Discount percentage */
  discount: number;
  /** Price after discount */
  discountPrice: number;
  /** Current stock quantity */
  inStock: number;
  /** Total sold quantity */
  sold: number;
  /** Average rating */
  rate: number;
  /** Override cost price for this batch */
  costPriceOverride?: ListInventoriesResponseDataItemCostPriceOverride;
  /** Batch number for tracking */
  batchNumber?: ListInventoriesResponseDataItemBatchNumber;
  /** Expiry date for perishable items */
  expiryDate?: ListInventoriesResponseDataItemExpiryDate;
  /** Warehouse code */
  warehouseCode?: ListInventoriesResponseDataItemWarehouseCode;
  /** Shelf code for location in warehouse */
  shelfCode?: ListInventoriesResponseDataItemShelfCode;
  /** Lead time in days to prepare for shipping */
  leadTimeDays?: ListInventoriesResponseDataItemLeadTimeDays;
  /** Harmonized System code for customs */
  hsCode?: ListInventoriesResponseDataItemHsCode;
  /** Country of manufacture/origin */
  originCountry?: ListInventoriesResponseDataItemOriginCountry;
  /** Gross weight including packaging (kg) */
  packageWeight?: ListInventoriesResponseDataItemPackageWeight;
  /** Packaged dimensions: length x width x height */
  packageDimensions?: ListInventoriesResponseDataItemPackageDimensions;
  /** Low stock alert threshold */
  lowStockThreshold: number;
  /** Whether stock is below threshold */
  isLowStock: boolean;
  /** number of row in list table */
  rowNumber: number;
};
