/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ListLocationsResponseDetails } from './listLocationsResponseDetails';
import type { ListLocationsResponseFiltersItem } from './listLocationsResponseFiltersItem';
import type { ListLocationsResponseDataItem } from './listLocationsResponseDataItem';

/**
 * List of locations response
 */
export type ListLocationsResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ListLocationsResponseDetails;
  filters: ListLocationsResponseFiltersItem[];
  data: ListLocationsResponseDataItem[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: ListLocationsResponseDetails;
  filters: ListLocationsResponseFiltersItem[];
  data: ListLocationsResponseDataItem[];
}, 'filters' | 'data'>>;
