/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListStoresResponseFiltersItemLabel } from './listStoresResponseFiltersItemLabel';
import type { ListStoresResponseFiltersItemModel } from './listStoresResponseFiltersItemModel';
import type { ListStoresResponseFiltersItemField } from './listStoresResponseFiltersItemField';
import type { ListStoresResponseFiltersItemAdvanced } from './listStoresResponseFiltersItemAdvanced';
import type { ListStoresResponseFiltersItemEnumOptions } from './listStoresResponseFiltersItemEnumOptions';

export type ListStoresResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ListStoresResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ListStoresResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ListStoresResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ListStoresResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ListStoresResponseFiltersItemEnumOptions;
};
