/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ListCategoryResponseDetails } from './listCategoryResponseDetails';
import type { ListCategoryResponseFiltersItem } from './listCategoryResponseFiltersItem';
import type { Category } from './category';

/**
 * Response schema for listing categories with pagination and metadata
 */
export type ListCategoryResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ListCategoryResponseDetails;
  filters: ListCategoryResponseFiltersItem[];
  /** Array of categories matching the query */
  data: Category[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: ListCategoryResponseDetails;
  filters: ListCategoryResponseFiltersItem[];
  /** Array of categories matching the query */
  data: Category[];
}, 'filters' | 'data'>>;
