/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ListAttributesResponseDetails } from './listAttributesResponseDetails';
import type { ListAttributesResponseFiltersItem } from './listAttributesResponseFiltersItem';
import type { ListAttributesResponseDataItem } from './listAttributesResponseDataItem';

/**
 * List of attributes response
 */
export type ListAttributesResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ListAttributesResponseDetails;
  filters: ListAttributesResponseFiltersItem[];
  data: ListAttributesResponseDataItem[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: ListAttributesResponseDetails;
  filters: ListAttributesResponseFiltersItem[];
  data: ListAttributesResponseDataItem[];
}, 'filters' | 'data'>>;
