/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListStoresResponseDataItemLogo } from "./listStoresResponseDataItemLogo";
import type { ListStoresResponseDataItemDescription } from "./listStoresResponseDataItemDescription";
import type { ListStoresResponseDataItemEmail } from "./listStoresResponseDataItemEmail";
import type { ListStoresResponseDataItemPhone } from "./listStoresResponseDataItemPhone";
import type { ListStoresResponseDataItemWebsite } from "./listStoresResponseDataItemWebsite";
import type { ListStoresResponseDataItemOwnerId } from "./listStoresResponseDataItemOwnerId";

export type ListStoresResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Store name (unique)
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * URL-friendly slug (unique, lowercase, hyphens only)
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-z0-9-]+$
   */
  slug: string;
  /** Store logo URL */
  logo?: ListStoresResponseDataItemLogo;
  /** Store description */
  description?: ListStoresResponseDataItemDescription;
  /** Business email (unique) */
  email?: ListStoresResponseDataItemEmail;
  /** Business phone (unique) */
  phone?: ListStoresResponseDataItemPhone;
  /** External website URL */
  website?: ListStoresResponseDataItemWebsite;
  /** Whether store is active */
  isActive: boolean;
  /** Platform approval status */
  isApproved: boolean;
  /** Owner user ID */
  ownerId?: ListStoresResponseDataItemOwnerId;
  /** number of row in list table */
  rowNumber: number;
};
