/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { ListColorResponseDetails } from "./listColorResponseDetails";
import type { ListColorResponseFiltersItem } from "./listColorResponseFiltersItem";
import type { ListColorResponseDataItem } from "./listColorResponseDataItem";

/**
 * Response schema for listing colors with pagination and metadata
 */
export type ListColorResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ListColorResponseDetails;
  filters: ListColorResponseFiltersItem[];
  /** Array of colors matching the query */
  data: ListColorResponseDataItem[];
} & Required<
    Pick<
      BaseResponse & {
        /** Pagination metadata */
        details?: ListColorResponseDetails;
        filters: ListColorResponseFiltersItem[];
        /** Array of colors matching the query */
        data: ListColorResponseDataItem[];
      },
      "filters" | "data"
    >
  >;
