/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ListStoreLocationsResponseDetails } from './listStoreLocationsResponseDetails';
import type { ListStoreLocationsResponseFiltersItem } from './listStoreLocationsResponseFiltersItem';
import type { ListStoreLocationsResponseDataItem } from './listStoreLocationsResponseDataItem';

/**
 * List of store-location assignments response
 */
export type ListStoreLocationsResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ListStoreLocationsResponseDetails;
  filters: ListStoreLocationsResponseFiltersItem[];
  data: ListStoreLocationsResponseDataItem[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: ListStoreLocationsResponseDetails;
  filters: ListStoreLocationsResponseFiltersItem[];
  data: ListStoreLocationsResponseDataItem[];
}, 'filters' | 'data'>>;
