/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListStoreLocationsResponseDataItemAssignedById } from "./listStoreLocationsResponseDataItemAssignedById";
import type { LocationType } from "./locationType";

export type ListStoreLocationsResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Store ID */
  storeId: string;
  /** Location ID */
  locationId: string;
  /** When this location was assigned to the store */
  assignedAt: string;
  /** User ID who assigned this location */
  assignedById?: ListStoreLocationsResponseDataItemAssignedById;
  /** Whether this assignment is currently active */
  isActive: boolean;
  /** Type of location assignment */
  type: LocationType;
  /** number of row in list table */
  rowNumber: number;
};
