/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListAttributesResponseFiltersItemLabel } from "./listAttributesResponseFiltersItemLabel";
import type { ListAttributesResponseFiltersItemModel } from "./listAttributesResponseFiltersItemModel";
import type { ListAttributesResponseFiltersItemField } from "./listAttributesResponseFiltersItemField";
import type { ListAttributesResponseFiltersItemAdvanced } from "./listAttributesResponseFiltersItemAdvanced";
import type { ListAttributesResponseFiltersItemEnumOptions } from "./listAttributesResponseFiltersItemEnumOptions";

export type ListAttributesResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ListAttributesResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ListAttributesResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ListAttributesResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ListAttributesResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ListAttributesResponseFiltersItemEnumOptions;
};
