/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListColorResponseDataItemDeletedAt } from "./listColorResponseDataItemDeletedAt";
import type { ListColorResponseDataItemEnName } from "./listColorResponseDataItemEnName";
import type { ListColorResponseDataItemDisplayName } from "./listColorResponseDataItemDisplayName";

export type ListColorResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: ListColorResponseDataItemDeletedAt;
  /**
   * Category name in native language
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /** English name for internationalization */
  enName?: ListColorResponseDataItemEnName;
  /** for marketing. e.g: 'Snow white' */
  displayName?: ListColorResponseDataItemDisplayName;
  /**
   * Hexadecimal color code (e.g., #FFFFFF, #FF5733)
   * @pattern ^#([0-9A-Fa-f]{3}){1,2}$
   */
  hex: string;
  /** Filter by active status */
  isActive: boolean;
  /** number of row in list table */
  rowNumber: number;
};
