/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListColorResponseFiltersItemLabel } from "./listColorResponseFiltersItemLabel";
import type { ListColorResponseFiltersItemModel } from "./listColorResponseFiltersItemModel";
import type { ListColorResponseFiltersItemField } from "./listColorResponseFiltersItemField";
import type { ListColorResponseFiltersItemAdvanced } from "./listColorResponseFiltersItemAdvanced";
import type { ListColorResponseFiltersItemEnumOptions } from "./listColorResponseFiltersItemEnumOptions";

export type ListColorResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ListColorResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ListColorResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ListColorResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ListColorResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ListColorResponseFiltersItemEnumOptions;
};
