/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { ListAttributeValuesResponseDetails } from "./listAttributeValuesResponseDetails";
import type { ListAttributeValuesResponseFiltersItem } from "./listAttributeValuesResponseFiltersItem";
import type { AttributeValue } from "./attributeValue";

/**
 * List of attribute values response
 */
export type ListAttributeValuesResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ListAttributeValuesResponseDetails;
  filters: ListAttributeValuesResponseFiltersItem[];
  data: AttributeValue[];
} & Required<
    Pick<
      BaseResponse & {
        /** Pagination metadata */
        details?: ListAttributeValuesResponseDetails;
        filters: ListAttributeValuesResponseFiltersItem[];
        data: AttributeValue[];
      },
      "filters" | "data"
    >
  >;
