/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

export type ListAttributeValuesResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Attribute value
   * @minLength 1
   * @maxLength 100
   */
  value: string;
  /** Parent attribute ID */
  attributeId: string;
  /** number of row in list table */
  rowNumber: number;
};
