/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListAttributeValuesResponseDataItemTextValue } from './listAttributeValuesResponseDataItemTextValue';
import type { ListAttributeValuesResponseDataItemDateValue } from './listAttributeValuesResponseDataItemDateValue';
import type { ListAttributeValuesResponseDataItemNumberValue } from './listAttributeValuesResponseDataItemNumberValue';
import type { ListAttributeValuesResponseDataItemBoolValue } from './listAttributeValuesResponseDataItemBoolValue';

export type ListAttributeValuesResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Attribute value */
  textValue?: ListAttributeValuesResponseDataItemTextValue;
  /** date AttributeValue */
  dateValue?: ListAttributeValuesResponseDataItemDateValue;
  /** number AttributeValue */
  numberValue?: ListAttributeValuesResponseDataItemNumberValue;
  /**  boolean AttributeValue */
  boolValue?: ListAttributeValuesResponseDataItemBoolValue;
  /** related attribute ID */
  attributeId: string;
  /** related variant ID */
  variantId: string;
  /** number of row in list table */
  rowNumber: number;
};
