/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListCategoryResponseDataItemDeletedAt } from './listCategoryResponseDataItemDeletedAt';
import type { ListCategoryResponseDataItemParentId } from './listCategoryResponseDataItemParentId';
import type { ListCategoryResponseDataItemIconUrl } from './listCategoryResponseDataItemIconUrl';
import type { ListCategoryResponseDataItemDesc } from './listCategoryResponseDataItemDesc';
import type { ListCategoryResponseDataItemIsActive } from './listCategoryResponseDataItemIsActive';
import type { ListCategoryResponseDataItemShowInMenu } from './listCategoryResponseDataItemShowInMenu';

export type ListCategoryResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: ListCategoryResponseDataItemDeletedAt;
  /**
   * Category name in native language
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * English name for internationalization
   * @minLength 2
   * @maxLength 50
   */
  enName: string;
  /** Parent category ID if exists */
  parentId?: ListCategoryResponseDataItemParentId;
  /** the level of category in hirarchy */
  level: number;
  /** Unit ID */
  unitId: string;
  /** Icon URL */
  iconUrl?: ListCategoryResponseDataItemIconUrl;
  /** Category description in native language */
  desc?: ListCategoryResponseDataItemDesc;
  /** Active status */
  isActive?: ListCategoryResponseDataItemIsActive;
  /** Show in menu status */
  showInMenu?: ListCategoryResponseDataItemShowInMenu;
  /** number of row in list table */
  rowNumber: number;
};
