/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListAttributesResponseDataItemType } from "./listAttributesResponseDataItemType";
import type { ListAttributesResponseDataItemUnit } from "./listAttributesResponseDataItemUnit";
import type { ListAttributesResponseDataItemIconUrl } from "./listAttributesResponseDataItemIconUrl";

export type ListAttributesResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Attribute title
   * @minLength 2
   * @maxLength 50
   */
  title: string;
  /** Attribute type */
  type: ListAttributesResponseDataItemType;
  /** Attribute type */
  unit?: ListAttributesResponseDataItemUnit;
  /** URL to attribute icon */
  iconUrl?: ListAttributesResponseDataItemIconUrl;
  /** Category ID this attribute belongs to */
  categoryId: string;
  /** number of row in list table */
  rowNumber: number;
};
