/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * The name of the model to search in.
 */
export type ListAttributeValuesResponseFiltersItemModel = string | null;
