/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListAttributeValuesResponseFiltersItemLabel } from "./listAttributeValuesResponseFiltersItemLabel";
import type { ListAttributeValuesResponseFiltersItemModel } from "./listAttributeValuesResponseFiltersItemModel";
import type { ListAttributeValuesResponseFiltersItemField } from "./listAttributeValuesResponseFiltersItemField";
import type { ListAttributeValuesResponseFiltersItemAdvanced } from "./listAttributeValuesResponseFiltersItemAdvanced";
import type { ListAttributeValuesResponseFiltersItemEnumOptions } from "./listAttributeValuesResponseFiltersItemEnumOptions";

export type ListAttributeValuesResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ListAttributeValuesResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ListAttributeValuesResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ListAttributeValuesResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ListAttributeValuesResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ListAttributeValuesResponseFiltersItemEnumOptions;
};
