/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListInventoryResponseFiltersItemLabel } from "./listInventoryResponseFiltersItemLabel";
import type { ListInventoryResponseFiltersItemModel } from "./listInventoryResponseFiltersItemModel";
import type { ListInventoryResponseFiltersItemField } from "./listInventoryResponseFiltersItemField";
import type { ListInventoryResponseFiltersItemAdvanced } from "./listInventoryResponseFiltersItemAdvanced";
import type { ListInventoryResponseFiltersItemEnumOptions } from "./listInventoryResponseFiltersItemEnumOptions";

export type ListInventoryResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ListInventoryResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ListInventoryResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ListInventoryResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ListInventoryResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ListInventoryResponseFiltersItemEnumOptions;
};
