/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListInventoryResponseDataItemGuaranteeId } from "./listInventoryResponseDataItemGuaranteeId";
import type { ListInventoryResponseDataItemInsuranceId } from "./listInventoryResponseDataItemInsuranceId";
import type { ListInventoryResponseDataItemLeasingId } from "./listInventoryResponseDataItemLeasingId";
import type { ListInventoryResponseDataItemChequeId } from "./listInventoryResponseDataItemChequeId";
import type { ListInventoryResponseDataItemCost } from "./listInventoryResponseDataItemCost";
import type { ListInventoryResponseDataItemExpiryDate } from "./listInventoryResponseDataItemExpiryDate";
import type { ListInventoryResponseDataItemWarehouseCode } from "./listInventoryResponseDataItemWarehouseCode";
import type { ListInventoryResponseDataItemShelfCode } from "./listInventoryResponseDataItemShelfCode";
import type { ListInventoryResponseDataItemHsCode } from "./listInventoryResponseDataItemHsCode";
import type { ListInventoryResponseDataItemOriginCountry } from "./listInventoryResponseDataItemOriginCountry";
import type { ListInventoryResponseDataItemPackageWeight } from "./listInventoryResponseDataItemPackageWeight";
import type { ListInventoryResponseDataItemPackageDimensions } from "./listInventoryResponseDataItemPackageDimensions";

export type ListInventoryResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Store ID */
  storeId: string;
  /** Location ID */
  locationId: string;
  /** Variant ID */
  variantId: string;
  /** Guarantee ID */
  guaranteeId?: ListInventoryResponseDataItemGuaranteeId;
  /** Insurance ID */
  insuranceId?: ListInventoryResponseDataItemInsuranceId;
  /** Leasing ID */
  leasingId?: ListInventoryResponseDataItemLeasingId;
  /** Cheque ID */
  chequeId?: ListInventoryResponseDataItemChequeId;
  /** Cost price */
  cost?: ListInventoryResponseDataItemCost;
  /** Base price */
  price: number;
  /**
   * Discount percentage
   * @minimum 0
   * @maximum 100
   */
  discountPercent: number;
  /** Price after discount (calculated) */
  discountPrice: number;
  /**
   * Current stock quantity
   * @minimum 0
   */
  inStock: number;
  /**
   * Total sold quantity
   * @minimum 0
   */
  sold: number;
  /**
   * Average rating
   * @minimum 0
   * @maximum 5
   */
  rate: number;
  /**
   * Low stock alert threshold
   * @minimum 0
   */
  lowStockThreshold: number;
  /** Expiry date for perishable items */
  expiryDate?: ListInventoryResponseDataItemExpiryDate;
  /** Warehouse code */
  warehouseCode?: ListInventoryResponseDataItemWarehouseCode;
  /** Shelf code for location in warehouse */
  shelfCode?: ListInventoryResponseDataItemShelfCode;
  /** Harmonized System code for customs */
  hsCode?: ListInventoryResponseDataItemHsCode;
  /** Country of manufacture/origin */
  originCountry?: ListInventoryResponseDataItemOriginCountry;
  /** Gross weight including packaging (kg) */
  packageWeight?: ListInventoryResponseDataItemPackageWeight;
  /** Packaged dimensions: length x width x height */
  packageDimensions?: ListInventoryResponseDataItemPackageDimensions;
  /** number of row in list table */
  rowNumber: number;
};
