/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListLocationsResponseDataItemStreetNumber } from './listLocationsResponseDataItemStreetNumber';
import type { ListLocationsResponseDataItemIsActive } from './listLocationsResponseDataItemIsActive';

export type ListLocationsResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Street name
   * @minLength 1
   */
  street: string;
  /** Street number */
  streetNumber?: ListLocationsResponseDataItemStreetNumber;
  /**
   * Postal/ZIP code
   * @minLength 3
   */
  postalCode: string;
  /** Province ID */
  provinceId: string;
  /** City ID */
  cityId: string;
  /** Whether the location is active */
  isActive: ListLocationsResponseDataItemIsActive;
  /** number of row in list table */
  rowNumber: number;
};
