/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ListLocationsResponseFiltersItemLabel } from "./listLocationsResponseFiltersItemLabel";
import type { ListLocationsResponseFiltersItemModel } from "./listLocationsResponseFiltersItemModel";
import type { ListLocationsResponseFiltersItemField } from "./listLocationsResponseFiltersItemField";
import type { ListLocationsResponseFiltersItemAdvanced } from "./listLocationsResponseFiltersItemAdvanced";
import type { ListLocationsResponseFiltersItemEnumOptions } from "./listLocationsResponseFiltersItemEnumOptions";

export type ListLocationsResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ListLocationsResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ListLocationsResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ListLocationsResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ListLocationsResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ListLocationsResponseFiltersItemEnumOptions;
};
