/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LocationStreetNumber } from './locationStreetNumber';
import type { LocationIsActive } from './locationIsActive';

/**
 * Location entity representing a physical address
 */
export interface Location {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Street name
   * @minLength 1
   */
  street: string;
  /** Street number */
  streetNumber?: LocationStreetNumber;
  /**
   * Postal/ZIP code
   * @minLength 3
   */
  postalCode: string;
  /** Province ID */
  provinceId: string;
  /** City ID */
  cityId: string;
  /** Whether the location is active */
  isActive: LocationIsActive;
}
