/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseError } from "./baseError";

export type NotfoundError = BaseError & {
  /** Error code */
  code: string;
} & Required<
    Pick<
      BaseError & {
        /** Error code */
        code: string;
      },
      "code"
    >
  >;
