/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { PostProductsBodyLabelsAnyOfItem } from "./postProductsBodyLabelsAnyOfItem";

/**
 * Connected label IDs
 */
export type PostProductsBodyLabels = PostProductsBodyLabelsAnyOfItem[] | null;
