/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { PricingTierDeletedAt } from "./pricingTierDeletedAt";
import type { PricingTierStandardMaxQuantity } from "./pricingTierStandardMaxQuantity";
import type { PricingTierPremiumMaxQuantity } from "./pricingTierPremiumMaxQuantity";
import type { PricingTierClientGroupId } from "./pricingTierClientGroupId";

/**
 * Volume-based pricing tiers for standard and premium
 */
export interface PricingTier {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: PricingTierDeletedAt;
  /** Associated variant ID */
  variantId: string;
  /**
   * Minimum quantity for standard customers
   * @minimum 1
   */
  standardMinQuantity: number;
  /** Maximum quantity for standard customers */
  standardMaxQuantity?: PricingTierStandardMaxQuantity;
  /**
   * Minimum quantity for premium customers
   * @minimum 1
   */
  premiumMinQuantity: number;
  /** Maximum quantity for premium customers */
  premiumMaxQuantity?: PricingTierPremiumMaxQuantity;
  /**
   * Price per unit
   * @minimum 0
   */
  price: number;
  /** Date when this pricing tier becomes active */
  provideDate: string;
  /** Customer group ID (optional) */
  clientGroupId?: PricingTierClientGroupId;
  /** Currency ID */
  currencyId: string;
}
