/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductListResponseDataItemDescriptionsAnyOfItem } from "./productListResponseDataItemDescriptionsAnyOfItem";

/**
 * Product descriptions
 */
export type ProductListResponseDataItemDescriptions =
  | ProductListResponseDataItemDescriptionsAnyOfItem[]
  | null;
