/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * UUID of the user who uploaded this media (for audit trail)
 */
export type ProductMediaUploadedById = string | null;
