/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { ProductMedia } from "./productMedia";

/**
 * Response schema for single product media operations
 */
export type ProductMediaResponse = BaseResponse & {
  data?: ProductMedia;
};
