/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductListResponseDataItemDeletedAt } from "./productListResponseDataItemDeletedAt";
import type { ProductListResponseDataItemAverageRating } from "./productListResponseDataItemAverageRating";
import type { ProductListResponseDataItemTotalReviews } from "./productListResponseDataItemTotalReviews";
import type { ProductListResponseDataItemLabels } from "./productListResponseDataItemLabels";
import type { ProductListResponseDataItemMedias } from "./productListResponseDataItemMedias";
import type { ProductListResponseDataItemDescriptions } from "./productListResponseDataItemDescriptions";

export type ProductListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: ProductListResponseDataItemDeletedAt;
  /**
   * Product name in native language
   * @minLength 2
   * @maxLength 200
   */
  name: string;
  /**
   * English product name for SEO and international users
   * @minLength 2
   * @maxLength 200
   */
  enName: string;
  /** Category ID this product belongs to */
  categoryId: string;
  /** Brand ID (optional) */
  brandId: string;
  /** Whether product is active and visible */
  isActive: boolean;
  /** Computed average rating from 0 to 5, from inventory reviews */
  averageRating?: ProductListResponseDataItemAverageRating;
  /** Total number of reviews for the product */
  totalReviews?: ProductListResponseDataItemTotalReviews;
  /** Connected label IDs */
  labels?: ProductListResponseDataItemLabels;
  /** Product media */
  medias?: ProductListResponseDataItemMedias;
  /** Product descriptions */
  descriptions?: ProductListResponseDataItemDescriptions;
  /** number of row in list table */
  rowNumber: number;
};
