/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Computed average rating from 0 to 5, from inventory reviews
 */
export type ProductListResponseDataItemAverageRating = number | null;
