/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductMediaThumbnailUrl } from './productMediaThumbnailUrl';
import type { ProductMediaAltText } from './productMediaAltText';
import type { ProductMediaCaption } from './productMediaCaption';
import type { ProductMediaMimetype } from './productMediaMimetype';
import type { ProductMediaUploadedById } from './productMediaUploadedById';

/**
 * Complete product media entity with comprehensive metadata
 */
export interface ProductMedia {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** UUID of the associated product */
  productId: string;
  /**
   * Relative or absolute URL path to the media file
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /** Optional thumbnail URL for quick preview (auto-generated for videos) */
  thumbnailUrl?: ProductMediaThumbnailUrl;
  /** Alternative text for accessibility and SEO optimization */
  altText?: ProductMediaAltText;
  /** Detailed caption or description of the media content */
  caption?: ProductMediaCaption;
  /** Comprehensive list of supported MIME types for product media */
  mimetype: ProductMediaMimetype;
  /**
   * Display order (0 = primary/main media, higher numbers for secondary)
   * @minimum 0
   * @maximum 999
   */
  order: number;
  /** UUID of the user who uploaded this media (for audit trail) */
  uploadedById?: ProductMediaUploadedById;
}
