/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductDeletedAt } from './productDeletedAt';
import type { ProductAverageRating } from './productAverageRating';
import type { ProductTotalReviews } from './productTotalReviews';
import type { ProductLabels } from './productLabels';
import type { ProductMedias } from './productMedias';
import type { ProductDescriptions } from './productDescriptions';

/**
 * Complete mobile phone product entity
 */
export interface Product {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: ProductDeletedAt;
  /**
   * Product name in native language
   * @minLength 2
   * @maxLength 200
   */
  name: string;
  /**
   * English product name for SEO and international users
   * @minLength 2
   * @maxLength 200
   */
  enName: string;
  /** Category ID this product belongs to */
  categoryId: string;
  /** Brand ID (optional) */
  brandId: string;
  /** Whether product is active and visible */
  isActive: boolean;
  /** Computed average rating from 0 to 5, from inventory reviews */
  averageRating?: ProductAverageRating;
  /** Total number of reviews for the product */
  totalReviews?: ProductTotalReviews;
  /** Connected label IDs */
  labels?: ProductLabels;
  /** Product media */
  medias?: ProductMedias;
  /** Product descriptions */
  descriptions?: ProductDescriptions;
}
