/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductDescriptionMediaSide } from "./productDescriptionMediaSide";
import type { ProductDescriptionMediaId } from "./productDescriptionMediaId";

/**
 * Product description section with optional media
 */
export interface ProductDescription {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /**
   * Description section title
   * @minLength 2
   * @maxLength 100
   */
  title: string;
  /**
   * Detailed description content
   * @minLength 2
   * @maxLength 2000
   */
  text: string;
  /** Media placement side */
  mediaSide: ProductDescriptionMediaSide;
  /** Optional ID referencing a ProductMedia entity */
  mediaId?: ProductDescriptionMediaId;
  /** Associated product ID */
  productId: string;
}
