/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ProductListResponseDetails } from './productListResponseDetails';
import type { ProductListResponseFiltersItem } from './productListResponseFiltersItem';
import type { ProductListResponseDataItem } from './productListResponseDataItem';

/**
 * Paginated list of mobile devices
 */
export type ProductListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ProductListResponseDetails;
  filters: ProductListResponseFiltersItem[];
  data: ProductListResponseDataItem[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: ProductListResponseDetails;
  filters: ProductListResponseFiltersItem[];
  data: ProductListResponseDataItem[];
}, 'filters' | 'data'>>;
