/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ProductDescription } from './productDescription';

export type ProductDescriptionResponse = BaseResponse & {
  data: ProductDescription;
} & Required<Pick<BaseResponse & {
  data: ProductDescription;
}, 'data'>>;
