/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Total number of reviews for the product
 */
export type ProductTotalReviews = number | null;
