/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductDescriptionsAnyOfItemMediaSide } from "./productDescriptionsAnyOfItemMediaSide";

export type ProductDescriptionsAnyOfItem = {
  id: string;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaSide: ProductDescriptionsAnyOfItemMediaSide;
  /** @nullable */
  mediaId: string | null;
};
