/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductLabelsAnyOfItem } from './productLabelsAnyOfItem';

/**
 * Connected label IDs
 */
export type ProductLabels = ProductLabelsAnyOfItem[] | null;
