/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProductListResponseDataItemDescriptionsAnyOfItemMediaSide } from "./productListResponseDataItemDescriptionsAnyOfItemMediaSide";

export type ProductListResponseDataItemDescriptionsAnyOfItem = {
  id: string;
  /** @nullable */
  text: string | null;
  /** @nullable */
  mediaSide: ProductListResponseDataItemDescriptionsAnyOfItemMediaSide;
  /** @nullable */
  mediaId: string | null;
};
