/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { ProvinceListResponseFiltersItemLabel } from './provinceListResponseFiltersItemLabel';
import type { ProvinceListResponseFiltersItemModel } from './provinceListResponseFiltersItemModel';
import type { ProvinceListResponseFiltersItemField } from './provinceListResponseFiltersItemField';
import type { ProvinceListResponseFiltersItemAdvanced } from './provinceListResponseFiltersItemAdvanced';
import type { ProvinceListResponseFiltersItemEnumOptions } from './provinceListResponseFiltersItemEnumOptions';

export type ProvinceListResponseFiltersItem = {
  /** The key representing the service associated with the filter. */
  service: string;
  /** A user-friendly label for the filter. */
  label?: ProvinceListResponseFiltersItemLabel;
  /** Indicates whether the filter is currently open (active). */
  open: boolean;
  /** The type of filter, which determines how it behaves. */
  type: string;
  /** The name of the model to search in. */
  model?: ProvinceListResponseFiltersItemModel;
  /** The scope of the search for this filter, providing context for filtering. */
  field?: ProvinceListResponseFiltersItemField;
  /** Indicates if this filter is an advanced filter. */
  advanced?: ProvinceListResponseFiltersItemAdvanced;
  /** Indicates the filter options that are based on an enumeration. */
  enumOptions?: ProvinceListResponseFiltersItemEnumOptions;
};
