/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from './baseResponse';
import type { ProvinceListResponseDetails } from './provinceListResponseDetails';
import type { ProvinceListResponseFiltersItem } from './provinceListResponseFiltersItem';
import type { Province } from './province';

/**
 * Response for list province operations
 */
export type ProvinceListResponse = BaseResponse & {
  /** Pagination metadata */
  details?: ProvinceListResponseDetails;
  filters: ProvinceListResponseFiltersItem[];
  /** Array of provinces matching the query */
  data: Province[];
} & Required<Pick<BaseResponse & {
  /** Pagination metadata */
  details?: ProvinceListResponseDetails;
  filters: ProvinceListResponseFiltersItem[];
  /** Array of provinces matching the query */
  data: Province[];
}, 'filters' | 'data'>>;
