/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

export type RefreshTokenResponseData = {
  /**
   * Access token
   * @minLength 1
   */
  accessToken: string;
  /**
   * Refresh token
   * @minLength 1
   */
  refreshToken: string;
};
