/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProductInputLabelsAnyOfItem } from "./updateProductInputLabelsAnyOfItem";

/**
 * Connected label IDs
 */
export type UpdateProductInputLabels =
  | UpdateProductInputLabelsAnyOfItem[]
  | null;
