/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLabelInputPageId } from './updateLabelInputPageId';

/**
 * Label update payload
 */
export interface UpdateLabelInput {
  /**
   * Label name
   * @minLength 2
   * @maxLength 50
   */
  name?: string;
  /** Optional Associated page ID */
  pageId?: UpdateLabelInputPageId;
}
