/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePricingTierInputStandardMaxQuantity } from "./updatePricingTierInputStandardMaxQuantity";
import type { UpdatePricingTierInputPremiumMaxQuantity } from "./updatePricingTierInputPremiumMaxQuantity";
import type { UpdatePricingTierInputClientGroupId } from "./updatePricingTierInputClientGroupId";

/**
 * Volume-based pricing tiers for standard and premium
 */
export interface UpdatePricingTierInput {
  /** Associated variant ID */
  variantId?: string;
  /**
   * Minimum quantity for standard customers
   * @minimum 1
   */
  standardMinQuantity?: number;
  /** Maximum quantity for standard customers */
  standardMaxQuantity?: UpdatePricingTierInputStandardMaxQuantity;
  /**
   * Minimum quantity for premium customers
   * @minimum 1
   */
  premiumMinQuantity?: number;
  /** Maximum quantity for premium customers */
  premiumMaxQuantity?: UpdatePricingTierInputPremiumMaxQuantity;
  /**
   * Price per unit
   * @minimum 0
   */
  price?: number;
  /** Date when this pricing tier becomes active */
  provideDate?: string;
  /** Customer group ID (optional) */
  clientGroupId?: UpdatePricingTierInputClientGroupId;
  /** Currency ID */
  currencyId?: string;
}
