/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateStoreInputLogo } from "./updateStoreInputLogo";
import type { UpdateStoreInputDescription } from "./updateStoreInputDescription";
import type { UpdateStoreInputEmail } from "./updateStoreInputEmail";
import type { UpdateStoreInputPhone } from "./updateStoreInputPhone";
import type { UpdateStoreInputWebsite } from "./updateStoreInputWebsite";
import type { UpdateStoreInputOwnerId } from "./updateStoreInputOwnerId";

/**
 * Store update payload
 */
export interface UpdateStoreInput {
  /**
   * Store name (unique)
   * @minLength 2
   * @maxLength 100
   */
  name?: string;
  /** Store logo URL */
  logo?: UpdateStoreInputLogo;
  /** Store description */
  description?: UpdateStoreInputDescription;
  /** Business email (unique) */
  email?: UpdateStoreInputEmail;
  /** Business phone (unique) */
  phone?: UpdateStoreInputPhone;
  /** External website URL */
  website?: UpdateStoreInputWebsite;
  /** Whether store is active */
  isActive?: boolean;
  /** Platform approval status */
  isApproved?: boolean;
  /** Owner user ID */
  ownerId?: UpdateStoreInputOwnerId;
}
