/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { Unit } from "./unit";

/**
 * Response format for unit update operations
 */
export interface UpdateUnitResponse {
  /** Operation status */
  success: boolean;
  data: Unit;
}
