/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Attribute type
 */
export type UpdateAttributeInputType =
  (typeof UpdateAttributeInputType)[keyof typeof UpdateAttributeInputType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAttributeInputType = {
  select: "select",
  multiselect: "multiselect",
  text: "text",
  number: "number",
  boolean: "boolean",
} as const;
