/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateInventoryInputGuaranteeId } from "./updateInventoryInputGuaranteeId";
import type { UpdateInventoryInputInsuranceId } from "./updateInventoryInputInsuranceId";
import type { UpdateInventoryInputLeasingId } from "./updateInventoryInputLeasingId";
import type { UpdateInventoryInputChequeId } from "./updateInventoryInputChequeId";
import type { UpdateInventoryInputCost } from "./updateInventoryInputCost";
import type { UpdateInventoryInputExpiryDate } from "./updateInventoryInputExpiryDate";
import type { UpdateInventoryInputWarehouseCode } from "./updateInventoryInputWarehouseCode";
import type { UpdateInventoryInputShelfCode } from "./updateInventoryInputShelfCode";
import type { UpdateInventoryInputHsCode } from "./updateInventoryInputHsCode";
import type { UpdateInventoryInputOriginCountry } from "./updateInventoryInputOriginCountry";
import type { UpdateInventoryInputPackageWeight } from "./updateInventoryInputPackageWeight";
import type { UpdateInventoryInputPackageDimensions } from "./updateInventoryInputPackageDimensions";

/**
 * Inventory update payload
 */
export interface UpdateInventoryInput {
  /** Store ID */
  storeId?: string;
  /** Location ID */
  locationId?: string;
  /** Variant ID */
  variantId?: string;
  /** Guarantee ID */
  guaranteeId?: UpdateInventoryInputGuaranteeId;
  /** Insurance ID */
  insuranceId?: UpdateInventoryInputInsuranceId;
  /** Leasing ID */
  leasingId?: UpdateInventoryInputLeasingId;
  /** Cheque ID */
  chequeId?: UpdateInventoryInputChequeId;
  /** Cost price */
  cost?: UpdateInventoryInputCost;
  /** Base price */
  price?: number;
  /**
   * Discount percentage
   * @minimum 0
   * @maximum 100
   */
  discountPercent?: number;
  /** Price after discount (calculated) */
  discountPrice?: number;
  /**
   * Current stock quantity
   * @minimum 0
   */
  inStock?: number;
  /**
   * Low stock alert threshold
   * @minimum 0
   */
  lowStockThreshold?: number;
  /** Expiry date for perishable items */
  expiryDate?: UpdateInventoryInputExpiryDate;
  /** Warehouse code */
  warehouseCode?: UpdateInventoryInputWarehouseCode;
  /** Shelf code for location in warehouse */
  shelfCode?: UpdateInventoryInputShelfCode;
  /** Harmonized System code for customs */
  hsCode?: UpdateInventoryInputHsCode;
  /** Country of manufacture/origin */
  originCountry?: UpdateInventoryInputOriginCountry;
  /** Gross weight including packaging (kg) */
  packageWeight?: UpdateInventoryInputPackageWeight;
  /** Packaged dimensions: length x width x height */
  packageDimensions?: UpdateInventoryInputPackageDimensions;
}
