/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAttributeInputType } from './updateAttributeInputType';
import type { UpdateAttributeInputUnit } from './updateAttributeInputUnit';
import type { UpdateAttributeInputIconUrl } from './updateAttributeInputIconUrl';

/**
 * Attribute update payload
 */
export interface UpdateAttributeInput {
  /**
   * Attribute title
   * @minLength 2
   * @maxLength 50
   */
  title?: string;
  /** Attribute type */
  type?: UpdateAttributeInputType;
  /** Attribute type */
  unit?: UpdateAttributeInputUnit;
  /** URL to attribute icon */
  iconUrl?: UpdateAttributeInputIconUrl;
  /** Category ID this attribute belongs to */
  categoryId?: string;
}
