/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { LocationType } from './locationType';

/**
 * Store-Location assignment update payload
 */
export interface UpdateStoreLocationInput {
  /** Store ID */
  storeId?: string;
  /** Location ID */
  locationId?: string;
  /** Whether this assignment is currently active */
  isActive?: boolean;
  /** Type of location assignment */
  type?: LocationType;
}
