/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Duration in months (optional)
 */
export type UpdateInsuranceInputMonths = number | null;
