/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProductDescriptionInputMediaSide } from "./updateProductDescriptionInputMediaSide";
import type { UpdateProductDescriptionInputMediaId } from "./updateProductDescriptionInputMediaId";

/**
 * Update product description fields
 */
export interface UpdateProductDescriptionInput {
  /**
   * Description section title
   * @minLength 2
   * @maxLength 100
   */
  title?: string;
  /**
   * Detailed description content
   * @minLength 2
   * @maxLength 2000
   */
  text?: string;
  /** Media placement side */
  mediaSide?: UpdateProductDescriptionInputMediaSide;
  /** Optional ID referencing a ProductMedia entity */
  mediaId?: UpdateProductDescriptionInputMediaId;
  /** Associated product ID */
  productId?: string;
}
