/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateGuaranteeInputStart } from "./updateGuaranteeInputStart";
import type { UpdateGuaranteeInputMonths } from "./updateGuaranteeInputMonths";
import type { UpdateGuaranteeInputDays } from "./updateGuaranteeInputDays";
import type { UpdateGuaranteeInputLogo } from "./updateGuaranteeInputLogo";
import type { UpdateGuaranteeInputProviderName } from "./updateGuaranteeInputProviderName";
import type { UpdateGuaranteeInputProviderAddress } from "./updateGuaranteeInputProviderAddress";
import type { UpdateGuaranteeInputProviderPhone } from "./updateGuaranteeInputProviderPhone";
import type { UpdateGuaranteeInputProviderCode } from "./updateGuaranteeInputProviderCode";
import type { UpdateGuaranteeInputTermsUrl } from "./updateGuaranteeInputTermsUrl";
import type { UpdateGuaranteeInputClaimProcess } from "./updateGuaranteeInputClaimProcess";
import type { UpdateGuaranteeInputResponseTime } from "./updateGuaranteeInputResponseTime";
import type { UpdateGuaranteeInputSepidarGuaranteeId } from "./updateGuaranteeInputSepidarGuaranteeId";

/**
 * Product warranty/guarantee entity
 */
export interface UpdateGuaranteeInput {
  /**
   * Guarantee title displayed to customer
   * @minLength 2
   * @maxLength 200
   */
  title?: string;
  /** Start date of guarantee validity */
  start?: UpdateGuaranteeInputStart;
  /** Duration in months (optional — use with days) */
  months?: UpdateGuaranteeInputMonths;
  /** Duration in days (optional — use with months) */
  days?: UpdateGuaranteeInputDays;
  /** Logo URL of guarantee provider */
  logo?: UpdateGuaranteeInputLogo;
  /** Name of warranty provider */
  providerName?: UpdateGuaranteeInputProviderName;
  /** Physical address of provider */
  providerAddress?: UpdateGuaranteeInputProviderAddress;
  /** Contact phone of provider */
  providerPhone?: UpdateGuaranteeInputProviderPhone;
  /** Internal provider code */
  providerCode?: UpdateGuaranteeInputProviderCode;
  /** URL to full terms and conditions */
  termsUrl?: UpdateGuaranteeInputTermsUrl;
  /** Can be claimed internationally? */
  isInternational?: boolean;
  /** How to claim this guarantee */
  claimProcess?: UpdateGuaranteeInputClaimProcess;
  /** Max days to respond to claim */
  responseTime?: UpdateGuaranteeInputResponseTime;
  /** Is this guarantee active for new sales? */
  isActive?: boolean;
  /** Display order priority */
  sortOrder?: number;
  /** Sepidar system reference ID */
  sepidarGuaranteeId?: UpdateGuaranteeInputSepidarGuaranteeId;
  /** Is this guarantee registered with tax authority? */
  isRegisteredWithTax?: boolean;
}
