/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLeasingInputDescription } from './updateLeasingInputDescription';
import type { UpdateLeasingInputCurrency } from './updateLeasingInputCurrency';
import type { UpdateLeasingInputIsActive } from './updateLeasingInputIsActive';
import type { UpdateLeasingInputBankId } from './updateLeasingInputBankId';
import type { UpdateLeasingInputCurrencyId } from './updateLeasingInputCurrencyId';
import type { UpdateLeasingInputContractTemplateUrl } from './updateLeasingInputContractTemplateUrl';
import type { UpdateLeasingInputTotalLeaseAmount } from './updateLeasingInputTotalLeaseAmount';
import type { UpdateLeasingInputAccountingRefId } from './updateLeasingInputAccountingRefId';
import type { UpdateLeasingInputIsRegisteredWithTax } from './updateLeasingInputIsRegisteredWithTax';

/**
 * Product leasing plan for B2B/B2C
 */
export interface UpdateLeasingInput {
  /**
   * Leasing plan title
   * @minLength 2
   * @maxLength 200
   */
  title?: string;
  /** Detailed description of leasing terms */
  description?: UpdateLeasingInputDescription;
  /**
   * Duration in months
   * @minimum 1
   */
  months?: number;
  /**
   * Name of the leasing provider (bank / FinTech)
   * @minLength 1
   * @maxLength 120
   */
  providerName?: string;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  firstPaymentPercent?: number;
  /**
   * Percentage of product price paid upfront
   * @minimum 0
   * @maximum 100
   */
  sellerLeasingProfit?: number;
  /** Currency code */
  currency?: UpdateLeasingInputCurrency;
  /** Is this leasing plan active? */
  isActive?: UpdateLeasingInputIsActive;
  /** Display priority (descending) */
  sortOrder?: number;
  /** Associated bank ID */
  bankId?: UpdateLeasingInputBankId;
  /** Associated currency ID */
  currencyId?: UpdateLeasingInputCurrencyId;
  /** URL to lease contract template */
  contractTemplateUrl?: UpdateLeasingInputContractTemplateUrl;
  /** Total lease amount (including all payments) */
  totalLeaseAmount?: UpdateLeasingInputTotalLeaseAmount;
  /** External accounting system reference ID */
  accountingRefId?: UpdateLeasingInputAccountingRefId;
  /** Registered with tax authority? */
  isRegisteredWithTax?: UpdateLeasingInputIsRegisteredWithTax;
}
