/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProductInputBrandId } from "./updateProductInputBrandId";
import type { UpdateProductInputLabels } from "./updateProductInputLabels";
import type { UpdateProductInputMedias } from "./updateProductInputMedias";
import type { UpdateProductInputDescriptions } from "./updateProductInputDescriptions";

/**
 * Complete mobile phone product entity
 */
export interface UpdateProductInput {
  /**
   * Product name in native language
   * @minLength 2
   * @maxLength 200
   */
  name?: string;
  /**
   * English product name for SEO and international users
   * @minLength 2
   * @maxLength 200
   */
  enName?: string;
  /** Category ID this product belongs to */
  categoryId?: string;
  /** Brand ID (optional) */
  brandId?: UpdateProductInputBrandId;
  /** Whether product is active and visible */
  isActive?: boolean;
  /** Connected label IDs */
  labels?: UpdateProductInputLabels;
  /** Product media */
  medias?: UpdateProductInputMedias;
  /** Product descriptions */
  descriptions?: UpdateProductInputDescriptions;
}
