/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCityAbb } from './updateCityAbb';

export interface UpdateCity {
  /**
   * City name
   * @minLength 2
   * @maxLength 100
   */
  name?: string;
  /** City abbreviation */
  abb?: UpdateCityAbb;
  /** Province ID */
  provinceId?: string;
}
