/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateBrandInputEnName } from './updateBrandInputEnName';
import type { UpdateBrandInputLogoUrl } from './updateBrandInputLogoUrl';
import type { UpdateBrandInputWebsite } from './updateBrandInputWebsite';
import type { UpdateBrandInputDescription } from './updateBrandInputDescription';

export interface UpdateBrandInput {
  /**
   * Brand name in native language
   * @minLength 2
   * @maxLength 100
   */
  name?: string;
  /** English brand name */
  enName?: UpdateBrandInputEnName;
  /** Logo image URL */
  logoUrl?: UpdateBrandInputLogoUrl;
  /** Official website */
  website?: UpdateBrandInputWebsite;
  /** Brand description */
  description?: UpdateBrandInputDescription;
  /** Sorting priority */
  sortOrder?: number;
  /** Filter by active status */
  isActive?: boolean;
}
