/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Currency entity for pricing
 */
export interface UpdateCurrencyInput {
  /**
   * Currency name
   * @minLength 2
   * @maxLength 100
   */
  name?: string;
  /**
   * Currency symbol
   * @minLength 1
   * @maxLength 10
   */
  symbol?: string;
  /** Is this the default currency? */
  isDefault?: boolean;
}
