/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCityInputAbb } from './updateCityInputAbb';

export interface UpdateCityInput {
  /**
   * City name in native language
   * @minLength 2
   * @maxLength 100
   */
  name?: string;
  /** City abbreviation (e.g., THR for Tehran) */
  abb?: UpdateCityInputAbb;
  /** Associated province ID */
  provinceId?: string;
}
