/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponse } from "./baseResponse";
import type { Variant } from "./variant";

/**
 * Response for single variant operations
 */
export type VariantResponse = BaseResponse & {
  VariantSchema: Variant;
} & Required<
    Pick<
      BaseResponse & {
        VariantSchema: Variant;
      },
      "VariantSchema"
    >
  >;
