/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { VariantDeletedAt } from './variantDeletedAt';
import type { VariantBarcode } from './variantBarcode';
import type { VariantMpn } from './variantMpn';
import type { VariantTitleOverride } from './variantTitleOverride';
import type { VariantDescriptionOverride } from './variantDescriptionOverride';
import type { VariantSlug } from './variantSlug';
import type { VariantMetaTitle } from './variantMetaTitle';
import type { VariantMetaDescription } from './variantMetaDescription';

/**
 * Product variant entity
 */
export interface Variant {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: VariantDeletedAt;
  /** Associated product ID */
  productId: string;
  /** Color ID */
  colorId: string;
  /**
   * Stock Keeping Unit (unique)
   * @minLength 2
   * @maxLength 100
   */
  sku: string;
  /**
   * Stock Keeping Unit (unique)
   * @minLength 2
   * @maxLength 100
   */
  publicId: string;
  /** Barcode (EAN/UPC) */
  barcode?: VariantBarcode;
  /** Manufacturer Part Number */
  mpn?: VariantMpn;
  /** Custom title for this variant */
  titleOverride?: VariantTitleOverride;
  /** Custom description */
  descriptionOverride?: VariantDescriptionOverride;
  /** Is variant active? */
  isActive: boolean;
  /** Is variant approved for sale? */
  isApproved: boolean;
  /** URL-friendly slug */
  slug?: VariantSlug;
  /** SEO meta title */
  metaTitle?: VariantMetaTitle;
  /** SEO meta description */
  metaDescription?: VariantMetaDescription;
  /** Unique attribute combination key */
  attributeComboKey: string;
}
