/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import type { VariantListResponseDataItemDeletedAt } from './variantListResponseDataItemDeletedAt';
import type { VariantListResponseDataItemBarcode } from './variantListResponseDataItemBarcode';
import type { VariantListResponseDataItemMpn } from './variantListResponseDataItemMpn';
import type { VariantListResponseDataItemTitleOverride } from './variantListResponseDataItemTitleOverride';
import type { VariantListResponseDataItemDescriptionOverride } from './variantListResponseDataItemDescriptionOverride';
import type { VariantListResponseDataItemSlug } from './variantListResponseDataItemSlug';
import type { VariantListResponseDataItemMetaTitle } from './variantListResponseDataItemMetaTitle';
import type { VariantListResponseDataItemMetaDescription } from './variantListResponseDataItemMetaDescription';

export type VariantListResponseDataItem = {
  /** Unique identifier (UUIDv4) */
  id: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** Deletion timestamp (ISO 8601) when soft deleted */
  deletedAt?: VariantListResponseDataItemDeletedAt;
  /** Associated product ID */
  productId: string;
  /** Color ID */
  colorId: string;
  /**
   * Stock Keeping Unit (unique)
   * @minLength 2
   * @maxLength 100
   */
  sku: string;
  /**
   * Stock Keeping Unit (unique)
   * @minLength 2
   * @maxLength 100
   */
  publicId: string;
  /** Barcode (EAN/UPC) */
  barcode?: VariantListResponseDataItemBarcode;
  /** Manufacturer Part Number */
  mpn?: VariantListResponseDataItemMpn;
  /** Custom title for this variant */
  titleOverride?: VariantListResponseDataItemTitleOverride;
  /** Custom description */
  descriptionOverride?: VariantListResponseDataItemDescriptionOverride;
  /** Is variant active? */
  isActive: boolean;
  /** Is variant approved for sale? */
  isApproved: boolean;
  /** URL-friendly slug */
  slug?: VariantListResponseDataItemSlug;
  /** SEO meta title */
  metaTitle?: VariantListResponseDataItemMetaTitle;
  /** SEO meta description */
  metaDescription?: VariantListResponseDataItemMetaDescription;
  /** Unique attribute combination key */
  attributeComboKey: string;
  /** number of row in list table */
  rowNumber: number;
};
