/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Create a new leasing plan
 */
export const postLeasingsBodyTitleMin = 2;

export const postLeasingsBodyTitleMax = 200;
export const postLeasingsBodyDescriptionMaxOne = 500;
export const postLeasingsBodyProviderNameMax = 120;
export const postLeasingsBodyFirstPaymentPercentMin = 0;

export const postLeasingsBodyFirstPaymentPercentMax = 100;
export const postLeasingsBodySellerLeasingProfitMin = 0;

export const postLeasingsBodySellerLeasingProfitMax = 100;
export const postLeasingsBodyCurrencyMaxOne = 10;
export const postLeasingsBodyIsActiveDefaultOne = true;export const postLeasingsBodyContractTemplateUrlMaxOne = 1000;
export const postLeasingsBodyAccountingRefIdMaxOne = 200;


export const postLeasingsBody = zod.object({
  "title": zod.coerce.string().min(postLeasingsBodyTitleMin).max(postLeasingsBodyTitleMax).describe('Leasing plan title'),
  "description": zod.union([zod.coerce.string().max(postLeasingsBodyDescriptionMaxOne),zod.null()]).optional().describe('Detailed description of leasing terms'),
  "months": zod.coerce.number().min(1).describe('Duration in months'),
  "providerName": zod.coerce.string().min(1).max(postLeasingsBodyProviderNameMax).describe('Name of the leasing provider (bank / FinTech)'),
  "firstPaymentPercent": zod.coerce.number().min(postLeasingsBodyFirstPaymentPercentMin).max(postLeasingsBodyFirstPaymentPercentMax).describe('Percentage of product price paid upfront'),
  "sellerLeasingProfit": zod.coerce.number().min(postLeasingsBodySellerLeasingProfitMin).max(postLeasingsBodySellerLeasingProfitMax).describe('Percentage of product price paid upfront'),
  "currency": zod.union([zod.coerce.string().max(postLeasingsBodyCurrencyMaxOne),zod.null()]).optional().describe('Currency code'),
  "isActive": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Is this leasing plan active?'),
  "sortOrder": zod.coerce.number().describe('Display priority (descending)'),
  "bankId": zod.union([zod.uuid(),zod.null()]).optional().describe('Associated bank ID'),
  "currencyId": zod.union([zod.uuid(),zod.null()]).optional().describe('Associated currency ID'),
  "contractTemplateUrl": zod.union([zod.url().max(postLeasingsBodyContractTemplateUrlMaxOne),zod.null()]).optional().describe('URL to lease contract template'),
  "totalLeaseAmount": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Total lease amount (including all payments)'),
  "accountingRefId": zod.union([zod.coerce.string().max(postLeasingsBodyAccountingRefIdMaxOne),zod.null()]).optional().describe('External accounting system reference ID'),
  "isRegisteredWithTax": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Registered with tax authority?')
}).describe('Product leasing plan for B2B/B2C')

/**
 * Get all leasing plans with pagination and filtering
 */
export const getLeasingsQueryFieldDefaultOne = "createdAt";
export const getLeasingsQueryFieldMaxOne = 200;
export const getLeasingsQueryOrderDefaultOne = "desc";export const getLeasingsQuerySkipMin = 0;
export const getLeasingsQueryLimitMax = 20;
export const getLeasingsQueryTitleMaxOne = 200;


export const getLeasingsQueryParams = zod.object({
  "field": zod.union([zod.coerce.string().max(getLeasingsQueryFieldMaxOne),zod.null()]).optional().describe('Field to sort by'),
  "order": zod.union([zod.enum(['asc', 'desc']),zod.null()]).optional().describe('Sort order'),
  "skip": zod.coerce.number().min(getLeasingsQuerySkipMin).describe('Number of records to skip'),
  "limit": zod.coerce.number().min(1).max(getLeasingsQueryLimitMax).describe('Maximum number of records to return'),
  "deletedAt": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Optional date input, usually null'),
  "title": zod.union([zod.coerce.string().max(getLeasingsQueryTitleMaxOne),zod.null()]).optional().describe('Filter by leasing title'),
  "bankId": zod.union([zod.uuid(),zod.null()]).optional().describe('Filter by bank ID'),
  "isActive": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Filter by active status'),
  "minMonths": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Minimum lease duration (months)'),
  "maxMonths": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Maximum lease duration (months)')
})

export const getLeasingsResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('Paginated list of leasing plans')

export const getLeasingsIdParams = zod.object({
  "id": zod.uuid().describe('Unique variant identifier')
})

export const getLeasingsIdResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('Response for single leasing operations')

export const patchLeasingsIdParams = zod.object({
  "id": zod.uuid().describe('Unique variant identifier')
})

export const patchLeasingsIdBodyTitleMin = 2;

export const patchLeasingsIdBodyTitleMax = 200;
export const patchLeasingsIdBodyDescriptionMaxOne = 500;
export const patchLeasingsIdBodyProviderNameMax = 120;
export const patchLeasingsIdBodyFirstPaymentPercentMin = 0;

export const patchLeasingsIdBodyFirstPaymentPercentMax = 100;
export const patchLeasingsIdBodySellerLeasingProfitMin = 0;

export const patchLeasingsIdBodySellerLeasingProfitMax = 100;
export const patchLeasingsIdBodyCurrencyMaxOne = 10;
export const patchLeasingsIdBodyIsActiveDefaultOne = true;export const patchLeasingsIdBodyContractTemplateUrlMaxOne = 1000;
export const patchLeasingsIdBodyAccountingRefIdMaxOne = 200;


export const patchLeasingsIdBody = zod.object({
  "title": zod.coerce.string().min(patchLeasingsIdBodyTitleMin).max(patchLeasingsIdBodyTitleMax).optional().describe('Leasing plan title'),
  "description": zod.union([zod.coerce.string().max(patchLeasingsIdBodyDescriptionMaxOne),zod.null()]).optional().describe('Detailed description of leasing terms'),
  "months": zod.coerce.number().min(1).optional().describe('Duration in months'),
  "providerName": zod.coerce.string().min(1).max(patchLeasingsIdBodyProviderNameMax).optional().describe('Name of the leasing provider (bank / FinTech)'),
  "firstPaymentPercent": zod.coerce.number().min(patchLeasingsIdBodyFirstPaymentPercentMin).max(patchLeasingsIdBodyFirstPaymentPercentMax).optional().describe('Percentage of product price paid upfront'),
  "sellerLeasingProfit": zod.coerce.number().min(patchLeasingsIdBodySellerLeasingProfitMin).max(patchLeasingsIdBodySellerLeasingProfitMax).optional().describe('Percentage of product price paid upfront'),
  "currency": zod.union([zod.coerce.string().max(patchLeasingsIdBodyCurrencyMaxOne),zod.null()]).optional().describe('Currency code'),
  "isActive": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Is this leasing plan active?'),
  "sortOrder": zod.coerce.number().optional().describe('Display priority (descending)'),
  "bankId": zod.union([zod.uuid(),zod.null()]).optional().describe('Associated bank ID'),
  "currencyId": zod.union([zod.uuid(),zod.null()]).optional().describe('Associated currency ID'),
  "contractTemplateUrl": zod.union([zod.url().max(patchLeasingsIdBodyContractTemplateUrlMaxOne),zod.null()]).optional().describe('URL to lease contract template'),
  "totalLeaseAmount": zod.union([zod.coerce.number(),zod.null()]).optional().describe('Total lease amount (including all payments)'),
  "accountingRefId": zod.union([zod.coerce.string().max(patchLeasingsIdBodyAccountingRefIdMaxOne),zod.null()]).optional().describe('External accounting system reference ID'),
  "isRegisteredWithTax": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Registered with tax authority?')
}).describe('Product leasing plan for B2B/B2C')

export const patchLeasingsIdResponse = zod.object({
  "success": zod.union([zod.coerce.boolean(),zod.null()]).optional().describe('Operation status')
}).describe('Standard API response format').describe('Response for single leasing operations')

export const deleteLeasingsIdParams = zod.object({
  "id": zod.uuid().describe('Unique variant identifier')
})

