/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const postProductsBodyNameMin = 2;

export const postProductsBodyNameMax = 200;
export const postProductsBodyEnNameMin = 2;

export const postProductsBodyEnNameMax = 200;
export const postProductsBodyIsActiveDefault = true;

export const postProductsBody = zod
  .object({
    name: zod.coerce
      .string()
      .min(postProductsBodyNameMin)
      .max(postProductsBodyNameMax)
      .describe("Product name in native language"),
    enName: zod.coerce
      .string()
      .min(postProductsBodyEnNameMin)
      .max(postProductsBodyEnNameMax)
      .describe("English product name for SEO and international users"),
    categoryId: zod.uuid().describe("Category ID this product belongs to"),
    brandId: zod
      .union([zod.uuid(), zod.null()])
      .optional()
      .describe("Brand ID (optional)"),
    isActive: zod.coerce
      .boolean()
      .default(postProductsBodyIsActiveDefault)
      .describe("Whether product is active and visible"),
    labels: zod
      .union([
        zod.array(
          zod.object({
            id: zod.uuid(),
          }),
        ),
        zod.null(),
      ])
      .optional()
      .describe("Connected label IDs"),
    medias: zod
      .union([
        zod.array(
          zod.object({
            id: zod.uuid(),
            url: zod.url(),
            altText: zod.coerce.string().nullable(),
            caption: zod.coerce.string().nullable(),
          }),
        ),
        zod.null(),
      ])
      .optional()
      .describe("Product media"),
    descriptions: zod
      .union([
        zod.array(
          zod.object({
            id: zod.uuid(),
            text: zod.coerce.string().nullable(),
            mediaSide: zod
              .union([
                zod.literal("LEFT"),
                zod.literal("CENTER"),
                zod.literal("RIGHT"),
                zod.literal(null),
              ])
              .nullable(),
            mediaId: zod.uuid().nullable(),
          }),
        ),
        zod.null(),
      ])
      .optional()
      .describe("Product descriptions"),
  })
  .describe("Complete mobile phone product entity");

/**
 * Get all products with pagination and filtering
 */
export const getProductsQuerySkipMin = 0;
export const getProductsQueryLimitMax = 20;
export const getProductsQueryNameMaxOne = 50;
export const getProductsQueryEnNameMaxOne = 50;

export const getProductsQueryParams = zod.object({
  skip: zod.coerce
    .number()
    .min(getProductsQuerySkipMin)
    .describe("Number of records to skip"),
  limit: zod.coerce
    .number()
    .min(1)
    .max(getProductsQueryLimitMax)
    .describe("Maximum number of records to return"),
  deletedAt: zod
    .union([zod.iso.datetime({}), zod.null()])
    .optional()
    .describe("Optional date input, usually null"),
  name: zod
    .union([zod.coerce.string().max(getProductsQueryNameMaxOne), zod.null()])
    .optional()
    .describe("Filter products by name (partial match)"),
  enName: zod
    .union([zod.coerce.string().max(getProductsQueryEnNameMaxOne), zod.null()])
    .optional()
    .describe("Filter products by name (partial match)"),
  categoryId: zod
    .union([zod.uuid(), zod.null()])
    .optional()
    .describe("Filter products by category ID"),
  brandId: zod
    .union([zod.uuid(), zod.null()])
    .optional()
    .describe("Brand ID (optional)"),
  isActive: zod
    .union([zod.coerce.boolean(), zod.null()])
    .optional()
    .describe("Filter products by active status"),
  labels: zod
    .array(zod.uuid())
    .optional()
    .describe("Filter products by associated labels (array of UUIDs)"),
});

export const getProductsResponse = zod
  .object({
    success: zod
      .union([zod.coerce.boolean(), zod.null()])
      .optional()
      .describe("Operation status"),
  })
  .describe("Standard API response format")
  .describe("Paginated list of mobile devices");

export const getProductsIdParams = zod.object({
  id: zod.uuid().describe("Product ID"),
});

export const getProductsIdResponse = zod
  .object({
    success: zod
      .union([zod.coerce.boolean(), zod.null()])
      .optional()
      .describe("Operation status"),
  })
  .describe("Standard API response format")
  .describe("Response for single country operations");

export const patchProductsIdParams = zod.object({
  id: zod.uuid().describe("Product ID"),
});

export const patchProductsIdBodyNameMin = 2;

export const patchProductsIdBodyNameMax = 200;
export const patchProductsIdBodyEnNameMin = 2;

export const patchProductsIdBodyEnNameMax = 200;
export const patchProductsIdBodyIsActiveDefault = true;

export const patchProductsIdBody = zod
  .object({
    name: zod.coerce
      .string()
      .min(patchProductsIdBodyNameMin)
      .max(patchProductsIdBodyNameMax)
      .optional()
      .describe("Product name in native language"),
    enName: zod.coerce
      .string()
      .min(patchProductsIdBodyEnNameMin)
      .max(patchProductsIdBodyEnNameMax)
      .optional()
      .describe("English product name for SEO and international users"),
    categoryId: zod
      .uuid()
      .optional()
      .describe("Category ID this product belongs to"),
    brandId: zod
      .union([zod.uuid(), zod.null()])
      .optional()
      .describe("Brand ID (optional)"),
    isActive: zod.coerce
      .boolean()
      .default(patchProductsIdBodyIsActiveDefault)
      .describe("Whether product is active and visible"),
    labels: zod
      .union([
        zod.array(
          zod.object({
            id: zod.uuid(),
          }),
        ),
        zod.null(),
      ])
      .optional()
      .describe("Connected label IDs"),
    medias: zod
      .union([
        zod.array(
          zod.object({
            id: zod.uuid(),
            url: zod.url(),
            altText: zod.coerce.string().nullable(),
            caption: zod.coerce.string().nullable(),
          }),
        ),
        zod.null(),
      ])
      .optional()
      .describe("Product media"),
    descriptions: zod
      .union([
        zod.array(
          zod.object({
            id: zod.uuid(),
            text: zod.coerce.string().nullable(),
            mediaSide: zod
              .union([
                zod.literal("LEFT"),
                zod.literal("CENTER"),
                zod.literal("RIGHT"),
                zod.literal(null),
              ])
              .nullable(),
            mediaId: zod.uuid().nullable(),
          }),
        ),
        zod.null(),
      ])
      .optional()
      .describe("Product descriptions"),
  })
  .describe("Complete mobile phone product entity");

export const patchProductsIdResponseDataNameMin = 2;

export const patchProductsIdResponseDataNameMax = 200;
export const patchProductsIdResponseDataEnNameMin = 2;

export const patchProductsIdResponseDataEnNameMax = 200;
export const patchProductsIdResponseDataIsActiveDefault = true;

export const patchProductsIdResponse = zod
  .object({
    success: zod.coerce.boolean().describe("Operation status"),
    data: zod
      .object({
        id: zod.uuid().describe("Unique identifier (UUIDv4)"),
        createdAt: zod.iso
          .datetime({})
          .describe("Creation timestamp (ISO 8601)"),
        updatedAt: zod.iso
          .datetime({})
          .describe("Last update timestamp (ISO 8601)"),
        deletedAt: zod
          .union([zod.iso.datetime({}), zod.null()])
          .optional()
          .describe("Deletion timestamp (ISO 8601) when soft deleted"),
        name: zod.coerce
          .string()
          .min(patchProductsIdResponseDataNameMin)
          .max(patchProductsIdResponseDataNameMax)
          .describe("Product name in native language"),
        enName: zod.coerce
          .string()
          .min(patchProductsIdResponseDataEnNameMin)
          .max(patchProductsIdResponseDataEnNameMax)
          .describe("English product name for SEO and international users"),
        categoryId: zod.uuid().describe("Category ID this product belongs to"),
        brandId: zod
          .union([zod.uuid(), zod.null()])
          .optional()
          .describe("Brand ID (optional)"),
        isActive: zod.coerce
          .boolean()
          .describe("Whether product is active and visible"),
        averageRating: zod
          .union([zod.coerce.number(), zod.null()])
          .optional()
          .describe(
            "Computed average rating from 0 to 5, from inventory reviews",
          ),
        totalReviews: zod
          .union([zod.coerce.number(), zod.null()])
          .optional()
          .describe("Total number of reviews for the product"),
        labels: zod
          .union([
            zod.array(
              zod.object({
                id: zod.uuid(),
                name: zod.coerce.string(),
              }),
            ),
            zod.null(),
          ])
          .optional()
          .describe("Connected label IDs"),
        medias: zod
          .union([
            zod.array(
              zod.object({
                id: zod.uuid(),
                url: zod.url(),
                altText: zod.coerce.string().nullable(),
                caption: zod.coerce.string().nullable(),
              }),
            ),
            zod.null(),
          ])
          .optional()
          .describe("Product media"),
        descriptions: zod
          .union([
            zod.array(
              zod.object({
                id: zod.uuid(),
                text: zod.coerce.string().nullable(),
                mediaSide: zod
                  .union([
                    zod.literal("LEFT"),
                    zod.literal("CENTER"),
                    zod.literal("RIGHT"),
                    zod.literal(null),
                  ])
                  .nullable(),
                mediaId: zod.uuid().nullable(),
              }),
            ),
            zod.null(),
          ])
          .optional()
          .describe("Product descriptions"),
      })
      .describe("Complete mobile phone product entity"),
  })
  .describe("Response format for product update operations");

export const deleteProductsIdParams = zod.object({
  id: zod.uuid().describe("Product ID"),
});
