import { ReactQueryProvider } from "@lib/apis/ReactQueryProvider";
import { isLocaleRTL } from "@lib/configs/i18n";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ToastContainer } from "react-toastify";
import { vazir } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "ماهور الوند", template: "%s - ماهور الوند" },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const dir = isLocaleRTL(locale) ? "rtl" : "ltr";
  const messages = await getMessages({ locale });

  return (
    <html lang={locale} dir={dir}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="توضیح کوتاه و دقیق صفحه..." />
      </head>
      <body className={vazir.variable}>
        <ReactQueryProvider>
          <NextIntlClientProvider messages={messages} locale={locale}>
            {children}
            <ToastContainer position="bottom-center" autoClose={3000} />
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
