/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  ConflictError,
  CreateLocationInput,
  ErrorResponse,
  GetLocationsParams,
  InternalError,
  ListLocationsResponse,
  LocationResponse,
  NotfoundError,
  UpdateLocationInput
} from '../../schemas';

import { axiosInstance } from '../../configs/axios-instance';




/**
 * Create a new location
 */
export const postLocations = (
    createLocationInput: CreateLocationInput,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<LocationResponse>(
      {url: `/locations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLocationInput, signal
    },
      );
    }
  


export const getPostLocationsMutationOptions = <TError = ErrorResponse | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocations>>, TError,{data: CreateLocationInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postLocations>>, TError,{data: CreateLocationInput}, TContext> => {

const mutationKey = ['postLocations'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLocations>>, {data: CreateLocationInput}> = (props) => {
          const {data} = props ?? {};

          return  postLocations(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLocationsMutationResult = NonNullable<Awaited<ReturnType<typeof postLocations>>>
    export type PostLocationsMutationBody = CreateLocationInput
    export type PostLocationsMutationError = ErrorResponse | ConflictError | InternalError

    export const usePostLocations = <TError = ErrorResponse | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocations>>, TError,{data: CreateLocationInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLocations>>,
        TError,
        {data: CreateLocationInput},
        TContext
      > => {

      const mutationOptions = getPostLocationsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * List all locations with pagination and filters
 */
export const getLocations = (
    params: GetLocationsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ListLocationsResponse>(
      {url: `/locations`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetLocationsQueryKey = (params?: GetLocationsParams,) => {
    return [`/locations`, ...(params ? [params]: [])] as const;
    }

    
export const getGetLocationsQueryOptions = <TData = Awaited<ReturnType<typeof getLocations>>, TError = InternalError>(params: GetLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocations>>> = ({ signal }) => getLocations(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationsQueryResult = NonNullable<Awaited<ReturnType<typeof getLocations>>>
export type GetLocationsQueryError = InternalError


export function useGetLocations<TData = Awaited<ReturnType<typeof getLocations>>, TError = InternalError>(
 params: GetLocationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocations>>,
          TError,
          Awaited<ReturnType<typeof getLocations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocations<TData = Awaited<ReturnType<typeof getLocations>>, TError = InternalError>(
 params: GetLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocations>>,
          TError,
          Awaited<ReturnType<typeof getLocations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocations<TData = Awaited<ReturnType<typeof getLocations>>, TError = InternalError>(
 params: GetLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLocations<TData = Awaited<ReturnType<typeof getLocations>>, TError = InternalError>(
 params: GetLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocations>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get a single location by ID
 */
export const getLocationsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<LocationResponse>(
      {url: `/locations/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetLocationsIdQueryKey = (id?: string,) => {
    return [`/locations/${id}`] as const;
    }

    
export const getGetLocationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getLocationsId>>, TError = NotfoundError | InternalError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationsId>>> = ({ signal }) => getLocationsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationsId>>>
export type GetLocationsIdQueryError = NotfoundError | InternalError


export function useGetLocationsId<TData = Awaited<ReturnType<typeof getLocationsId>>, TError = NotfoundError | InternalError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationsId>>,
          TError,
          Awaited<ReturnType<typeof getLocationsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationsId<TData = Awaited<ReturnType<typeof getLocationsId>>, TError = NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationsId>>,
          TError,
          Awaited<ReturnType<typeof getLocationsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationsId<TData = Awaited<ReturnType<typeof getLocationsId>>, TError = NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLocationsId<TData = Awaited<ReturnType<typeof getLocationsId>>, TError = NotfoundError | InternalError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update a location
 */
export const patchLocationsId = (
    id: string,
    updateLocationInput: UpdateLocationInput,
 ) => {
      
      
      return axiosInstance<LocationResponse>(
      {url: `/locations/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateLocationInput
    },
      );
    }
  


export const getPatchLocationsIdMutationOptions = <TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchLocationsId>>, TError,{id: string;data: UpdateLocationInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchLocationsId>>, TError,{id: string;data: UpdateLocationInput}, TContext> => {

const mutationKey = ['patchLocationsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchLocationsId>>, {id: string;data: UpdateLocationInput}> = (props) => {
          const {id,data} = props ?? {};

          return  patchLocationsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchLocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchLocationsId>>>
    export type PatchLocationsIdMutationBody = UpdateLocationInput
    export type PatchLocationsIdMutationError = ErrorResponse | NotfoundError | ConflictError | InternalError

    export const usePatchLocationsId = <TError = ErrorResponse | NotfoundError | ConflictError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchLocationsId>>, TError,{id: string;data: UpdateLocationInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchLocationsId>>,
        TError,
        {id: string;data: UpdateLocationInput},
        TContext
      > => {

      const mutationOptions = getPatchLocationsIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Delete a location
 */
export const deleteLocationsId = (
    id: string,
 ) => {
      
      
      return axiosInstance<BaseResponse>(
      {url: `/locations/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteLocationsIdMutationOptions = <TError = NotfoundError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocationsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteLocationsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteLocationsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLocationsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteLocationsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteLocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLocationsId>>>
    
    export type DeleteLocationsIdMutationError = NotfoundError | InternalError

    export const useDeleteLocationsId = <TError = NotfoundError | InternalError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocationsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLocationsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteLocationsIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    